#!/usr/bin/env python3
"""
레벨별 단어 확장 스크립트 - 3000개+ 단어 생성
"""
import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
OUTPUT_FILE = DATA_DIR / "collected" / "vocabulary" / "expanded_vocabulary.json"

# A1 레벨 (500개)
A1_WORDS = [
    ("hello", "안녕하세요"), ("goodbye", "안녕히 가세요"), ("yes", "네"), ("no", "아니오"),
    ("please", "제발"), ("thank", "감사하다"), ("sorry", "미안한"), ("help", "돕다"),
    ("water", "물"), ("food", "음식"), ("eat", "먹다"), ("drink", "마시다"),
    ("go", "가다"), ("come", "오다"), ("see", "보다"), ("look", "보다"),
    ("want", "원하다"), ("need", "필요하다"), ("like", "좋아하다"), ("love", "사랑하다"),
    ("big", "큰"), ("small", "작은"), ("good", "좋은"), ("bad", "나쁜"),
    ("hot", "뜨거운"), ("cold", "차가운"), ("new", "새로운"), ("old", "오래된"),
    ("happy", "행복한"), ("sad", "슬픈"), ("tired", "피곤한"), ("hungry", "배고픈"),
    ("house", "집"), ("room", "방"), ("door", "문"), ("window", "창문"),
    ("table", "테이블"), ("chair", "의자"), ("bed", "침대"), ("book", "책"),
    ("pen", "펜"), ("paper", "종이"), ("phone", "전화기"), ("computer", "컴퓨터"),
    ("car", "자동차"), ("bus", "버스"), ("train", "기차"), ("plane", "비행기"),
    ("money", "돈"), ("time", "시간"), ("day", "날"), ("night", "밤"),
    ("morning", "아침"), ("afternoon", "오후"), ("evening", "저녁"), ("today", "오늘"),
    ("tomorrow", "내일"), ("yesterday", "어제"), ("week", "주"), ("month", "월"),
    ("year", "년"), ("name", "이름"), ("friend", "친구"), ("family", "가족"),
    ("mother", "어머니"), ("father", "아버지"), ("sister", "언니/여동생"), ("brother", "형/남동생"),
    ("child", "아이"), ("man", "남자"), ("woman", "여자"), ("people", "사람들"),
    ("work", "일하다"), ("study", "공부하다"), ("read", "읽다"), ("write", "쓰다"),
    ("speak", "말하다"), ("listen", "듣다"), ("understand", "이해하다"), ("know", "알다"),
    ("think", "생각하다"), ("feel", "느끼다"), ("try", "시도하다"), ("use", "사용하다"),
    ("make", "만들다"), ("take", "가져가다"), ("give", "주다"), ("get", "얻다"),
    ("put", "놓다"), ("find", "찾다"), ("ask", "묻다"), ("tell", "말하다"),
    ("say", "말하다"), ("call", "부르다"), ("wait", "기다리다"), ("stop", "멈추다"),
    ("start", "시작하다"), ("open", "열다"), ("close", "닫다"), ("buy", "사다"),
    ("sell", "팔다"), ("pay", "지불하다"), ("cost", "비용이 들다"), ("price", "가격"),
    ("shop", "가게"), ("store", "상점"), ("market", "시장"), ("restaurant", "식당"),
    ("hotel", "호텔"), ("airport", "공항"), ("station", "역"), ("street", "거리"),
    ("city", "도시"), ("country", "나라"), ("color", "색깔"), ("red", "빨간"),
    ("blue", "파란"), ("green", "초록"), ("yellow", "노란"), ("white", "흰"),
    ("black", "검은"), ("number", "숫자"), ("one", "하나"), ("two", "둘"),
    ("three", "셋"), ("four", "넷"), ("five", "다섯"), ("six", "여섯"),
    ("seven", "일곱"), ("eight", "여덟"), ("nine", "아홉"), ("ten", "열"),
    ("first", "첫 번째"), ("last", "마지막"), ("next", "다음"), ("same", "같은"),
    ("different", "다른"), ("all", "모든"), ("some", "일부"), ("many", "많은"),
    ("much", "많이"), ("few", "적은"), ("little", "작은/조금"), ("more", "더"),
    ("less", "덜"), ("very", "매우"), ("really", "정말"), ("always", "항상"),
    ("never", "절대"), ("sometimes", "때때로"), ("often", "자주"), ("usually", "보통"),
    ("here", "여기"), ("there", "거기"), ("where", "어디"), ("when", "언제"),
    ("what", "무엇"), ("who", "누구"), ("why", "왜"), ("how", "어떻게"),
    ("this", "이것"), ("that", "저것"), ("these", "이것들"), ("those", "저것들"),
    ("my", "나의"), ("your", "너의"), ("his", "그의"), ("her", "그녀의"),
    ("our", "우리의"), ("their", "그들의"), ("me", "나를"), ("you", "너를"),
    ("him", "그를"), ("them", "그들을"), ("us", "우리를"), ("myself", "나 자신"),
    ("can", "할 수 있다"), ("will", "~할 것이다"), ("would", "~할 것이다"), ("should", "~해야 한다"),
    ("must", "~해야 한다"), ("may", "~할지도 모른다"), ("might", "~할지도 모른다"), ("could", "~할 수 있었다"),
    ("have", "가지다"), ("has", "가지다"), ("had", "가졌다"), ("do", "하다"),
    ("does", "하다"), ("did", "했다"), ("be", "이다"), ("am", "~이다"),
    ("is", "~이다"), ("are", "~이다"), ("was", "~이었다"), ("were", "~이었다"),
    ("been", "~이었다"), ("being", "~이면서"), ("about", "~에 대해"), ("after", "~후에"),
    ("before", "~전에"), ("between", "~사이에"), ("during", "~동안"), ("for", "~를 위해"),
    ("from", "~로부터"), ("in", "~안에"), ("into", "~안으로"), ("of", "~의"),
    ("on", "~위에"), ("out", "밖으로"), ("over", "~위로"), ("through", "~를 통해"),
    ("to", "~에게"), ("under", "~아래에"), ("up", "위로"), ("down", "아래로"),
    ("with", "~와 함께"), ("without", "~없이"), ("and", "그리고"), ("but", "하지만"),
    ("or", "또는"), ("so", "그래서"), ("because", "왜냐하면"), ("if", "만약"),
    ("then", "그러면"), ("than", "~보다"), ("as", "~로서"), ("while", "~하는 동안"),
    ("animal", "동물"), ("dog", "개"), ("cat", "고양이"), ("bird", "새"),
    ("fish", "물고기"), ("tree", "나무"), ("flower", "꽃"), ("sun", "태양"),
    ("moon", "달"), ("star", "별"), ("sky", "하늘"), ("rain", "비"),
    ("snow", "눈"), ("wind", "바람"), ("weather", "날씨"), ("spring", "봄"),
    ("summer", "여름"), ("fall", "가을"), ("winter", "겨울"), ("head", "머리"),
    ("face", "얼굴"), ("eye", "눈"), ("ear", "귀"), ("nose", "코"),
    ("mouth", "입"), ("hand", "손"), ("foot", "발"), ("body", "몸"),
    ("heart", "심장/마음"), ("game", "게임"), ("music", "음악"), ("movie", "영화"),
    ("picture", "그림"), ("story", "이야기"), ("question", "질문"), ("answer", "대답"),
    ("problem", "문제"), ("idea", "아이디어"), ("thing", "것"), ("place", "장소"),
    ("part", "부분"), ("side", "옆"), ("end", "끝"), ("point", "점"),
    ("way", "방법"), ("life", "삶"), ("world", "세계"), ("school", "학교"),
    ("class", "수업"), ("teacher", "선생님"), ("student", "학생"), ("lesson", "수업"),
    ("test", "시험"), ("word", "단어"), ("sentence", "문장"), ("letter", "편지/글자"),
    ("apple", "사과"), ("banana", "바나나"), ("orange", "오렌지"), ("bread", "빵"),
    ("rice", "쌀/밥"), ("meat", "고기"), ("chicken", "닭고기"), ("egg", "계란"),
    ("milk", "우유"), ("coffee", "커피"), ("tea", "차"), ("juice", "주스"),
    ("breakfast", "아침식사"), ("lunch", "점심"), ("dinner", "저녁식사"), ("meal", "식사"),
    ("birthday", "생일"), ("holiday", "휴일"), ("party", "파티"), ("gift", "선물"),
    ("job", "직업"), ("office", "사무실"), ("meeting", "회의"), ("email", "이메일"),
    ("internet", "인터넷"), ("website", "웹사이트"), ("photo", "사진"), ("video", "비디오"),
    ("bag", "가방"), ("clothes", "옷"), ("shirt", "셔츠"), ("pants", "바지"),
    ("shoes", "신발"), ("hat", "모자"), ("jacket", "재킷"), ("dress", "드레스"),
    ("key", "열쇠"), ("wallet", "지갑"), ("watch", "시계"), ("glasses", "안경"),
    ("ticket", "티켓"), ("passport", "여권"), ("map", "지도"), ("address", "주소"),
    ("health", "건강"), ("doctor", "의사"), ("hospital", "병원"), ("medicine", "약"),
    ("sick", "아픈"), ("pain", "통증"), ("safe", "안전한"), ("dangerous", "위험한"),
    ("easy", "쉬운"), ("hard", "어려운"), ("fast", "빠른"), ("slow", "느린"),
    ("early", "이른"), ("late", "늦은"), ("long", "긴"), ("short", "짧은"),
    ("high", "높은"), ("low", "낮은"), ("heavy", "무거운"), ("light", "가벼운"),
    ("clean", "깨끗한"), ("dirty", "더러운"), ("quiet", "조용한"), ("loud", "시끄러운"),
    ("beautiful", "아름다운"), ("ugly", "못생긴"), ("young", "젊은"), ("rich", "부유한"),
    ("poor", "가난한"), ("free", "자유로운/무료의"), ("busy", "바쁜"), ("ready", "준비된"),
    ("wrong", "틀린"), ("right", "옳은/오른쪽"), ("left", "왼쪽"), ("front", "앞"),
    ("back", "뒤"), ("middle", "중간"), ("inside", "안쪽"), ("outside", "바깥쪽"),
    ("together", "함께"), ("alone", "혼자"), ("again", "다시"), ("already", "이미"),
    ("still", "아직"), ("yet", "아직"), ("just", "단지"), ("only", "오직"),
    ("also", "또한"), ("too", "너무/또한"), ("enough", "충분히"), ("almost", "거의"),
    ("maybe", "아마도"), ("probably", "아마"), ("certainly", "확실히"), ("sure", "확실한"),
    ("possible", "가능한"), ("impossible", "불가능한"), ("true", "진실인"), ("false", "거짓인"),
    ("real", "진짜의"), ("important", "중요한"), ("special", "특별한"), ("popular", "인기있는"),
    ("famous", "유명한"), ("interesting", "흥미로운"), ("boring", "지루한"), ("fun", "재미있는"),
    ("nice", "좋은"), ("kind", "친절한"), ("friendly", "다정한"), ("angry", "화난"),
    ("afraid", "두려운"), ("worried", "걱정하는"), ("surprised", "놀란"), ("excited", "신난"),
    ("become", "되다"), ("keep", "유지하다"), ("let", "허락하다"), ("leave", "떠나다"),
    ("stay", "머무르다"), ("live", "살다"), ("die", "죽다"), ("grow", "자라다"),
    ("change", "변하다"), ("move", "움직이다"), ("turn", "돌다"), ("run", "달리다"),
    ("walk", "걷다"), ("sit", "앉다"), ("stand", "서다"), ("sleep", "자다"),
    ("wake", "깨다"), ("play", "놀다"), ("sing", "노래하다"), ("dance", "춤추다"),
    ("swim", "수영하다"), ("fly", "날다"), ("drive", "운전하다"), ("ride", "타다"),
    ("catch", "잡다"), ("throw", "던지다"), ("hold", "잡다"), ("carry", "나르다"),
    ("pull", "당기다"), ("push", "밀다"), ("cut", "자르다"), ("break", "부수다"),
    ("fix", "고치다"), ("build", "짓다"), ("clean", "청소하다"), ("wash", "씻다"),
    ("cook", "요리하다"), ("bake", "굽다"), ("order", "주문하다"), ("serve", "제공하다"),
    ("choose", "선택하다"), ("decide", "결정하다"), ("plan", "계획하다"), ("prepare", "준비하다"),
    ("check", "확인하다"), ("count", "세다"), ("measure", "측정하다"), ("compare", "비교하다"),
    ("add", "더하다"), ("remove", "제거하다"), ("fill", "채우다"), ("empty", "비우다"),
    ("send", "보내다"), ("receive", "받다"), ("bring", "가져오다"), ("return", "돌아오다"),
    ("enter", "들어가다"), ("exit", "나가다"), ("arrive", "도착하다"), ("reach", "도달하다"),
    ("follow", "따라가다"), ("lead", "이끌다"), ("show", "보여주다"), ("hide", "숨기다"),
    ("appear", "나타나다"), ("disappear", "사라지다"), ("remember", "기억하다"), ("forget", "잊다"),
    ("learn", "배우다"), ("teach", "가르치다"), ("practice", "연습하다"), ("repeat", "반복하다"),
    ("explain", "설명하다"), ("describe", "묘사하다"), ("mean", "의미하다"), ("agree", "동의하다"),
    ("disagree", "동의하지 않다"), ("accept", "받아들이다"), ("refuse", "거절하다"), ("offer", "제안하다"),
    ("suggest", "제안하다"), ("recommend", "추천하다"), ("advise", "조언하다"), ("warn", "경고하다"),
    ("promise", "약속하다"), ("hope", "희망하다"), ("wish", "바라다"), ("expect", "기대하다"),
    ("believe", "믿다"), ("doubt", "의심하다"), ("guess", "추측하다"), ("wonder", "궁금해하다"),
]

# A2 레벨 (500개)
A2_WORDS = [
    ("adventure", "모험"), ("advice", "조언"), ("affect", "영향을 주다"), ("afford", "여유가 있다"),
    ("agent", "대리인"), ("airline", "항공사"), ("allow", "허락하다"), ("amazed", "놀란"),
    ("amazing", "놀라운"), ("amount", "양"), ("ancient", "고대의"), ("announce", "발표하다"),
    ("annoy", "짜증나게 하다"), ("anxious", "불안한"), ("apartment", "아파트"), ("apologize", "사과하다"),
    ("application", "신청서"), ("appointment", "약속"), ("appreciate", "감사하다"), ("approach", "접근하다"),
    ("appropriate", "적절한"), ("argue", "논쟁하다"), ("arrangement", "정리"), ("article", "기사"),
    ("artificial", "인공의"), ("assistant", "조수"), ("assume", "가정하다"), ("attach", "첨부하다"),
    ("attack", "공격하다"), ("attempt", "시도하다"), ("attend", "참석하다"), ("attention", "주의"),
    ("attitude", "태도"), ("attract", "끌어당기다"), ("audience", "청중"), ("available", "이용 가능한"),
    ("average", "평균"), ("avoid", "피하다"), ("awake", "깨어 있는"), ("award", "상"),
    ("awful", "끔찍한"), ("background", "배경"), ("balance", "균형"), ("basic", "기본적인"),
    ("basis", "기초"), ("battery", "배터리"), ("beach", "해변"), ("beat", "이기다"),
    ("behavior", "행동"), ("benefit", "이익"), ("block", "막다"), ("board", "판"),
    ("boat", "보트"), ("bomb", "폭탄"), ("bone", "뼈"), ("border", "경계"),
    ("borrow", "빌리다"), ("boss", "상사"), ("bottom", "바닥"), ("brain", "뇌"),
    ("brand", "브랜드"), ("brave", "용감한"), ("breast", "가슴"), ("breath", "호흡"),
    ("breathe", "숨쉬다"), ("brick", "벽돌"), ("bridge", "다리"), ("brief", "간단한"),
    ("bright", "밝은"), ("brilliant", "훌륭한"), ("broad", "넓은"), ("budget", "예산"),
    ("bullet", "총알"), ("burn", "태우다"), ("burst", "터지다"), ("cabinet", "캐비닛"),
    ("cable", "케이블"), ("calculate", "계산하다"), ("calendar", "달력"), ("calm", "차분한"),
    ("campaign", "캠페인"), ("cancel", "취소하다"), ("cancer", "암"), ("candidate", "후보자"),
    ("capable", "능력 있는"), ("capacity", "용량"), ("capital", "수도"), ("captain", "선장"),
    ("capture", "포착하다"), ("career", "경력"), ("careful", "조심하는"), ("careless", "부주의한"),
    ("carpet", "카펫"), ("cash", "현금"), ("cast", "던지다"), ("castle", "성"),
    ("casual", "캐주얼한"), ("category", "범주"), ("cause", "원인"), ("celebrate", "축하하다"),
    ("cell", "세포"), ("center", "중심"), ("central", "중앙의"), ("century", "세기"),
    ("ceremony", "의식"), ("chain", "사슬"), ("challenge", "도전"), ("champion", "챔피언"),
    ("chance", "기회"), ("channel", "채널"), ("chapter", "장"), ("character", "성격"),
    ("charge", "청구하다"), ("charity", "자선"), ("chart", "차트"), ("chase", "쫓다"),
    ("cheap", "싼"), ("cheat", "속이다"), ("chemical", "화학의"), ("chest", "가슴"),
    ("chief", "주요한"), ("childhood", "어린 시절"), ("chip", "칩"), ("chocolate", "초콜릿"),
    ("choice", "선택"), ("citizen", "시민"), ("civil", "시민의"), ("claim", "주장하다"),
    ("classic", "고전적인"), ("classroom", "교실"), ("clever", "영리한"), ("client", "고객"),
    ("climate", "기후"), ("climb", "오르다"), ("clock", "시계"), ("cloth", "천"),
    ("cloud", "구름"), ("club", "클럽"), ("clue", "단서"), ("coach", "코치"),
    ("coal", "석탄"), ("coast", "해안"), ("coat", "코트"), ("code", "코드"),
    ("coin", "동전"), ("collect", "수집하다"), ("college", "대학"), ("column", "열"),
    ("combine", "결합하다"), ("comedy", "코미디"), ("comfort", "편안함"), ("comfortable", "편안한"),
    ("command", "명령"), ("comment", "논평"), ("commercial", "상업적인"), ("commit", "저지르다"),
    ("committee", "위원회"), ("common", "일반적인"), ("communicate", "소통하다"), ("community", "공동체"),
    ("company", "회사"), ("compete", "경쟁하다"), ("competition", "경쟁"), ("complain", "불평하다"),
    ("complete", "완료하다"), ("complex", "복잡한"), ("concentrate", "집중하다"), ("concept", "개념"),
    ("concern", "관심사"), ("conclude", "결론짓다"), ("condition", "조건"), ("conduct", "수행하다"),
    ("conference", "회의"), ("confidence", "자신감"), ("confident", "자신감 있는"), ("confirm", "확인하다"),
    ("conflict", "충돌"), ("confuse", "혼란스럽게 하다"), ("connect", "연결하다"), ("conscious", "의식하는"),
    ("consider", "고려하다"), ("consist", "구성되다"), ("constant", "일정한"), ("construct", "건설하다"),
    ("contact", "연락하다"), ("contain", "포함하다"), ("content", "내용"), ("contest", "경연"),
    ("context", "맥락"), ("continue", "계속하다"), ("contract", "계약"), ("contrast", "대조"),
    ("contribute", "기여하다"), ("control", "통제하다"), ("convenient", "편리한"), ("convention", "관습"),
    ("conversation", "대화"), ("convert", "변환하다"), ("convince", "설득하다"), ("cookie", "쿠키"),
    ("cool", "시원한"), ("cope", "대처하다"), ("copy", "복사하다"), ("core", "핵심"),
    ("corner", "모퉁이"), ("correct", "올바른"), ("cotton", "면"), ("couch", "소파"),
    ("council", "의회"), ("couple", "커플"), ("courage", "용기"), ("course", "과정"),
    ("court", "법원"), ("cousin", "사촌"), ("cover", "덮다"), ("cow", "소"),
    ("crack", "금"), ("craft", "공예"), ("crash", "충돌하다"), ("crazy", "미친"),
    ("create", "창조하다"), ("creative", "창의적인"), ("creature", "생물"), ("credit", "신용"),
    ("crew", "승무원"), ("crime", "범죄"), ("criminal", "범죄자"), ("crisis", "위기"),
    ("critic", "비평가"), ("critical", "비판적인"), ("criticism", "비평"), ("crop", "작물"),
    ("cross", "건너다"), ("crowd", "군중"), ("cruel", "잔인한"), ("cry", "울다"),
    ("cultural", "문화적인"), ("culture", "문화"), ("cup", "컵"), ("cure", "치료하다"),
    ("curious", "호기심 많은"), ("current", "현재의"), ("curtain", "커튼"), ("curve", "곡선"),
    ("custom", "관습"), ("customer", "고객"), ("cycle", "주기"), ("daily", "매일의"),
    ("damage", "손상"), ("damp", "축축한"), ("danger", "위험"), ("dare", "감히 하다"),
    ("dark", "어두운"), ("data", "데이터"), ("database", "데이터베이스"), ("date", "날짜"),
    ("daughter", "딸"), ("dawn", "새벽"), ("deal", "거래"), ("dear", "친애하는"),
    ("debate", "토론"), ("debt", "빚"), ("decade", "십 년"), ("decent", "괜찮은"),
    ("declare", "선언하다"), ("decline", "감소하다"), ("decorate", "장식하다"), ("decrease", "감소하다"),
    ("deep", "깊은"), ("defeat", "패배시키다"), ("defend", "방어하다"), ("define", "정의하다"),
    ("degree", "정도"), ("delay", "지연"), ("delete", "삭제하다"), ("deliberate", "고의적인"),
    ("delicate", "섬세한"), ("delicious", "맛있는"), ("delight", "기쁨"), ("deliver", "배달하다"),
    ("demand", "요구하다"), ("democracy", "민주주의"), ("demonstrate", "시연하다"), ("deny", "부정하다"),
    ("department", "부서"), ("depend", "의존하다"), ("deposit", "예금"), ("depress", "우울하게 하다"),
    ("depth", "깊이"), ("derive", "유래하다"), ("desert", "사막"), ("deserve", "~할 자격이 있다"),
    ("design", "디자인"), ("desire", "욕망"), ("desk", "책상"), ("desperate", "절박한"),
    ("despite", "~에도 불구하고"), ("destination", "목적지"), ("destroy", "파괴하다"), ("detail", "세부사항"),
    ("detect", "감지하다"), ("determine", "결정하다"), ("develop", "개발하다"), ("device", "장치"),
    ("devote", "헌신하다"), ("dialogue", "대화"), ("diamond", "다이아몬드"), ("diary", "일기"),
    ("dictionary", "사전"), ("diet", "식단"), ("differ", "다르다"), ("digital", "디지털의"),
    ("dimension", "차원"), ("direct", "직접적인"), ("direction", "방향"), ("director", "감독"),
    ("dirt", "먼지"), ("disabled", "장애가 있는"), ("disadvantage", "불이익"), ("disappoint", "실망시키다"),
    ("disaster", "재난"), ("discipline", "훈육"), ("discount", "할인"), ("discover", "발견하다"),
    ("discuss", "토론하다"), ("disease", "질병"), ("dish", "접시"), ("dismiss", "해고하다"),
    ("display", "전시하다"), ("distance", "거리"), ("distant", "먼"), ("distinct", "뚜렷한"),
    ("distribute", "배포하다"), ("district", "지역"), ("disturb", "방해하다"), ("divide", "나누다"),
    ("divorce", "이혼"), ("document", "문서"), ("domestic", "국내의"), ("dominant", "지배적인"),
    ("donate", "기부하다"), ("double", "두 배의"), ("download", "다운로드하다"), ("downtown", "시내"),
    ("draft", "초안"), ("drag", "끌다"), ("drama", "드라마"), ("dramatic", "극적인"),
    ("draw", "그리다"), ("drawer", "서랍"), ("dream", "꿈"), ("drill", "훈련"),
    ("drop", "떨어뜨리다"), ("drug", "약물"), ("dry", "건조한"), ("due", "~할 예정인"),
    ("dull", "둔한"), ("dump", "버리다"), ("dust", "먼지"), ("duty", "의무"),
    ("eager", "열심인"), ("earn", "벌다"), ("earth", "지구"), ("earthquake", "지진"),
    ("eastern", "동쪽의"), ("economic", "경제의"), ("economy", "경제"), ("edge", "가장자리"),
    ("edition", "판"), ("editor", "편집자"), ("educate", "교육하다"), ("education", "교육"),
    ("effect", "효과"), ("effective", "효과적인"), ("efficient", "효율적인"), ("effort", "노력"),
    ("elderly", "나이 든"), ("elect", "선출하다"), ("election", "선거"), ("electric", "전기의"),
    ("electricity", "전기"), ("electronic", "전자의"), ("element", "요소"), ("elementary", "초등의"),
    ("elephant", "코끼리"), ("eliminate", "제거하다"), ("embarrass", "당황하게 하다"), ("emerge", "나타나다"),
    ("emergency", "비상"), ("emotion", "감정"), ("emotional", "감정적인"), ("emperor", "황제"),
    ("emphasis", "강조"), ("emphasize", "강조하다"), ("empire", "제국"), ("employ", "고용하다"),
]

# B1 레벨 (500개)
B1_WORDS = [
    ("abandon", "버리다"), ("abolish", "폐지하다"), ("abortion", "낙태"), ("absence", "부재"),
    ("absolute", "절대적인"), ("absorb", "흡수하다"), ("abstract", "추상적인"), ("abuse", "남용"),
    ("academic", "학문의"), ("accelerate", "가속하다"), ("accent", "억양"), ("acceptable", "수용 가능한"),
    ("access", "접근"), ("accessible", "접근 가능한"), ("accident", "사고"), ("accommodate", "수용하다"),
    ("accompany", "동반하다"), ("accomplish", "성취하다"), ("accord", "일치"), ("account", "계좌"),
    ("accountant", "회계사"), ("accurate", "정확한"), ("accuse", "고발하다"), ("achieve", "달성하다"),
    ("achievement", "성취"), ("acid", "산"), ("acknowledge", "인정하다"), ("acquire", "획득하다"),
    ("acquisition", "획득"), ("acre", "에이커"), ("activate", "활성화하다"), ("active", "활발한"),
    ("activist", "활동가"), ("actual", "실제의"), ("adapt", "적응하다"), ("addition", "추가"),
    ("additional", "추가의"), ("adequate", "적절한"), ("adjust", "조정하다"), ("administration", "행정"),
    ("administrative", "행정의"), ("admire", "존경하다"), ("admission", "입장"), ("admit", "인정하다"),
    ("adolescent", "청소년"), ("adopt", "채택하다"), ("adult", "성인"), ("advance", "발전"),
    ("advanced", "고급의"), ("advantage", "이점"), ("advertise", "광고하다"), ("advertisement", "광고"),
    ("advocate", "옹호하다"), ("aesthetic", "미적인"), ("affair", "사건"), ("affection", "애정"),
    ("affirmative", "긍정적인"), ("agenda", "의제"), ("aggressive", "공격적인"), ("aging", "노화"),
    ("agricultural", "농업의"), ("agriculture", "농업"), ("aid", "원조"), ("aim", "목표"),
    ("aircraft", "항공기"), ("alarm", "경보"), ("album", "앨범"), ("alcohol", "알코올"),
    ("alert", "경계하는"), ("alien", "외계인"), ("align", "정렬하다"), ("alike", "비슷한"),
    ("alliance", "동맹"), ("allocate", "할당하다"), ("alongside", "~와 함께"), ("alter", "바꾸다"),
    ("alternative", "대안"), ("altitude", "고도"), ("altogether", "전부"), ("aluminum", "알루미늄"),
    ("amateur", "아마추어"), ("ambassador", "대사"), ("ambition", "야망"), ("ambitious", "야심찬"),
    ("amend", "수정하다"), ("amendment", "수정"), ("amid", "~중에"), ("analyse", "분석하다"),
    ("analysis", "분석"), ("analyst", "분석가"), ("ancestor", "조상"), ("anchor", "닻"),
    ("angel", "천사"), ("angle", "각도"), ("anniversary", "기념일"), ("anonymous", "익명의"),
    ("anticipate", "예상하다"), ("anxiety", "불안"), ("apart", "따로"), ("apology", "사과"),
    ("apparatus", "장치"), ("apparent", "명백한"), ("appeal", "호소하다"), ("appetite", "식욕"),
    ("applause", "박수"), ("appliance", "가전제품"), ("applicable", "적용 가능한"), ("apply", "신청하다"),
    ("appoint", "임명하다"), ("approval", "승인"), ("approve", "승인하다"), ("approximate", "대략적인"),
    ("arbitrary", "임의적인"), ("architect", "건축가"), ("architecture", "건축"), ("area", "지역"),
    ("arise", "일어나다"), ("arm", "팔"), ("armed", "무장한"), ("armor", "갑옷"),
    ("army", "군대"), ("arrest", "체포하다"), ("arrival", "도착"), ("arrow", "화살"),
    ("ash", "재"), ("ashamed", "부끄러운"), ("aspect", "측면"), ("assault", "폭행"),
    ("assemble", "조립하다"), ("assembly", "집회"), ("assert", "주장하다"), ("assess", "평가하다"),
    ("assessment", "평가"), ("asset", "자산"), ("assign", "할당하다"), ("assignment", "과제"),
    ("assist", "돕다"), ("assistance", "지원"), ("associate", "연관짓다"), ("association", "협회"),
    ("atmosphere", "분위기"), ("atomic", "원자의"), ("attraction", "매력"), ("attribute", "속성"),
    ("auction", "경매"), ("audit", "감사"), ("author", "저자"), ("authority", "권위"),
    ("authorize", "인가하다"), ("auto", "자동차"), ("automatic", "자동의"), ("automobile", "자동차"),
    ("autumn", "가을"), ("availability", "가용성"), ("avenue", "대로"), ("await", "기다리다"),
    ("awareness", "인식"), ("awkward", "어색한"), ("bachelor", "학사/독신"), ("backing", "지원"),
    ("backward", "뒤로"), ("bacon", "베이컨"), ("bacteria", "박테리아"), ("badge", "배지"),
    ("badly", "심하게"), ("bake", "굽다"), ("ban", "금지"), ("band", "밴드"),
    ("banker", "은행가"), ("banking", "은행업"), ("bankrupt", "파산한"), ("banner", "현수막"),
    ("bare", "벌거벗은"), ("barely", "겨우"), ("bargain", "거래"), ("barrier", "장벽"),
    ("base", "기초"), ("basement", "지하실"), ("basket", "바구니"), ("bath", "목욕"),
    ("bathroom", "욕실"), ("battlefield", "전장"), ("bay", "만"), ("bean", "콩"),
    ("bear", "곰/견디다"), ("beard", "수염"), ("beast", "짐승"), ("beauty", "아름다움"),
    ("beef", "쇠고기"), ("beer", "맥주"), ("behalf", "~을 대신하여"), ("behave", "행동하다"),
    ("being", "존재"), ("belief", "믿음"), ("bell", "종"), ("belly", "배"),
    ("belong", "속하다"), ("below", "아래에"), ("belt", "벨트"), ("bench", "벤치"),
    ("bend", "구부리다"), ("beneath", "아래에"), ("beneficial", "유익한"), ("besides", "게다가"),
    ("bet", "내기하다"), ("betray", "배신하다"), ("betting", "도박"), ("beyond", "~을 넘어"),
    ("bias", "편견"), ("bid", "입찰"), ("billion", "십억"), ("bind", "묶다"),
    ("biological", "생물학적인"), ("biology", "생물학"), ("bite", "물다"), ("bitter", "쓴"),
    ("blade", "칼날"), ("blame", "비난하다"), ("blank", "빈"), ("blanket", "담요"),
    ("blast", "폭발"), ("bleed", "피를 흘리다"), ("blend", "섞다"), ("bless", "축복하다"),
    ("blind", "눈먼"), ("bloom", "꽃피다"), ("blow", "불다"), ("blueprint", "청사진"),
    ("boast", "자랑하다"), ("bold", "대담한"), ("bolt", "볼트"), ("bond", "결속"),
    ("bonus", "보너스"), ("boom", "호황"), ("boost", "촉진하다"), ("booth", "부스"),
    ("bore", "지루하게 하다"), ("bother", "귀찮게 하다"), ("bounce", "튀다"), ("bound", "~행의"),
    ("boundary", "경계"), ("bow", "절하다"), ("bowl", "그릇"), ("box", "상자"),
    ("boyfriend", "남자친구"), ("bracket", "괄호"), ("brake", "브레이크"), ("branch", "가지"),
    ("brass", "황동"), ("breach", "위반"), ("breakdown", "고장"), ("breakthrough", "돌파구"),
    ("breed", "품종"), ("brewery", "양조장"), ("bride", "신부"), ("brilliant", "훌륭한"),
    ("broadcast", "방송하다"), ("broker", "중개인"), ("bronze", "청동"), ("brush", "솔"),
    ("bubble", "거품"), ("bucket", "양동이"), ("buddy", "친구"), ("buffer", "완충"),
    ("bug", "벌레"), ("bulk", "대량"), ("bulletin", "회보"), ("bunch", "다발"),
    ("bundle", "묶음"), ("burden", "부담"), ("bureau", "사무국"), ("bureaucracy", "관료제"),
    ("burial", "매장"), ("bury", "묻다"), ("bush", "덤불"), ("butter", "버터"),
    ("buyer", "구매자"), ("cabinet", "내각"), ("cage", "우리"), ("calcium", "칼슘"),
    ("calling", "소명"), ("camera", "카메라"), ("camp", "야영지"), ("canal", "운하"),
    ("cancer", "암"), ("capability", "능력"), ("cape", "곶"), ("capitalism", "자본주의"),
    ("carbon", "탄소"), ("cargo", "화물"), ("carrier", "운송업자"), ("carve", "조각하다"),
    ("casino", "카지노"), ("casualty", "사상자"), ("catalog", "목록"), ("catastrophe", "재앙"),
    ("cattle", "소"), ("caution", "조심"), ("cease", "그치다"), ("ceiling", "천장"),
    ("cellular", "세포의"), ("cement", "시멘트"), ("cemetery", "묘지"), ("census", "인구조사"),
    ("chamber", "방"), ("chaos", "혼돈"), ("characteristic", "특성"), ("charm", "매력"),
    ("charter", "헌장"), ("cheap", "싼"), ("chef", "요리사"), ("chemistry", "화학"),
    ("cheque", "수표"), ("childhood", "어린 시절"), ("chill", "오한"), ("chin", "턱"),
    ("choir", "합창단"), ("chronic", "만성의"), ("chunk", "덩어리"), ("cigarette", "담배"),
    ("cinema", "영화관"), ("circuit", "회로"), ("circular", "원형의"), ("circulate", "순환하다"),
    ("circumstance", "상황"), ("cite", "인용하다"), ("civilian", "민간인"), ("civilization", "문명"),
    ("clarify", "명확히 하다"), ("clarity", "명확성"), ("clash", "충돌"), ("classification", "분류"),
    ("classify", "분류하다"), ("clause", "조항"), ("clay", "점토"), ("clinic", "진료소"),
    ("clinical", "임상의"), ("clip", "클립"), ("closure", "폐쇄"), ("cloth", "천"),
    ("clothing", "의류"), ("coalition", "연합"), ("coastal", "해안의"), ("cocktail", "칵테일"),
    ("cognitive", "인지의"), ("coincide", "일치하다"), ("coincidence", "우연의 일치"), ("collaboration", "협업"),
    ("collapse", "붕괴하다"), ("collar", "깃"), ("colleague", "동료"), ("collective", "집단의"),
    ("collision", "충돌"), ("colonial", "식민지의"), ("colony", "식민지"), ("combat", "전투"),
    ("combo", "조합"), ("commander", "사령관"), ("commence", "시작하다"), ("commerce", "상업"),
    ("commissioner", "위원"), ("commodity", "상품"), ("commonwealth", "영연방"), ("communism", "공산주의"),
    ("communist", "공산주의자"), ("compact", "소형의"), ("companion", "동반자"), ("comparable", "비교할 만한"),
    ("comparative", "비교의"), ("comparison", "비교"), ("compass", "나침반"), ("compel", "강요하다"),
    ("compensate", "보상하다"), ("compensation", "보상"), ("competence", "능력"), ("competent", "유능한"),
    ("competitive", "경쟁적인"), ("competitor", "경쟁자"), ("compile", "편집하다"), ("complaint", "불만"),
    ("complement", "보완물"), ("completion", "완료"), ("complexity", "복잡성"), ("compliance", "준수"),
    ("complicate", "복잡하게 하다"), ("complication", "합병증"), ("comply", "준수하다"), ("component", "구성요소"),
    ("compose", "구성하다"), ("composer", "작곡가"), ("composition", "구성"), ("compound", "복합물"),
    ("comprehensive", "포괄적인"), ("comprise", "포함하다"), ("compromise", "타협"), ("compute", "계산하다"),
    ("conceive", "상상하다"), ("conception", "개념"), ("concrete", "콘크리트"), ("condemn", "비난하다"),
    ("confer", "수여하다"), ("confess", "고백하다"), ("confession", "고백"), ("configuration", "구성"),
    ("confine", "가두다"), ("confirmation", "확인"), ("confrontation", "대결"), ("confusion", "혼란"),
    ("congress", "의회"), ("conjunction", "접속사"), ("consciousness", "의식"), ("consecutive", "연속적인"),
    ("consensus", "합의"), ("consent", "동의"), ("consequence", "결과"), ("conservation", "보존"),
    ("conservative", "보수적인"), ("considerable", "상당한"), ("considerably", "상당히"), ("consideration", "고려"),
    ("consistency", "일관성"), ("consistent", "일관된"), ("consolidate", "통합하다"), ("conspiracy", "음모"),
    ("constitute", "구성하다"), ("constitution", "헌법"), ("constitutional", "헌법의"), ("constraint", "제약"),
    ("consultation", "상담"), ("consumer", "소비자"), ("consumption", "소비"), ("contemporary", "현대의"),
    ("contempt", "경멸"), ("contend", "주장하다"), ("continent", "대륙"), ("continental", "대륙의"),
    ("contractor", "계약자"), ("contradiction", "모순"), ("contrary", "반대의"), ("contribution", "기여"),
    ("controversial", "논쟁적인"), ("controversy", "논쟁"), ("convention", "관습"), ("conventional", "전통적인"),
    ("conversion", "전환"), ("conviction", "확신"), ("cooperative", "협동적인"), ("coordinate", "조정하다"),
    ("coordination", "조정"), ("cop", "경찰"), ("copyright", "저작권"), ("cord", "끈"),
    ("corporate", "기업의"), ("corporation", "법인"), ("correction", "수정"), ("correlation", "상관관계"),
    ("correspond", "일치하다"), ("correspondence", "통신"), ("correspondent", "특파원"), ("corresponding", "해당하는"),
    ("corridor", "복도"), ("corrupt", "부패한"), ("corruption", "부패"), ("costume", "의상"),
    ("cottage", "오두막"), ("cotton", "면"), ("councillor", "의원"), ("counseling", "상담"),
    ("counselor", "상담사"), ("counterpart", "상대방"), ("countless", "무수한"), ("coup", "쿠데타"),
    ("coupling", "결합"), ("coupon", "쿠폰"), ("courtesy", "예의"), ("coverage", "보도"),
    ("craft", "공예"), ("crane", "크레인"), ("crawl", "기어가다"), ("creature", "생물"),
    ("credential", "자격증"), ("credibility", "신뢰성"), ("creek", "시내"), ("creep", "기어가다"),
    ("criterion", "기준"), ("critique", "비평"), ("crop", "작물"), ("crown", "왕관"),
    ("crucial", "중요한"), ("crude", "천연의"), ("cruise", "크루즈"), ("crush", "부수다"),
    ("crystal", "수정"), ("cultivate", "경작하다"), ("curiosity", "호기심"), ("curriculum", "교육과정"),
    ("custody", "양육권"), ("custom", "관습"), ("customs", "세관"), ("cute", "귀여운"),
]

# B2 레벨 (500개) - 축약
B2_WORDS = [
    ("abbreviation", "약어"), ("abolition", "폐지"), ("abrupt", "갑작스러운"), ("absurd", "터무니없는"),
    ("abundance", "풍부"), ("accelerate", "가속화하다"), ("accomplishment", "업적"), ("accountability", "책임"),
    ("accumulate", "축적하다"), ("accuracy", "정확성"), ("accusation", "고발"), ("acquaint", "알리다"),
    ("acute", "급성의"), ("adaptation", "적응"), ("addiction", "중독"), ("adherence", "고수"),
    ("adjacent", "인접한"), ("adolescence", "청소년기"), ("adoption", "채택"), ("adverse", "불리한"),
    ("advocacy", "옹호"), ("aerial", "공중의"), ("affiliate", "제휴하다"), ("affirmation", "확언"),
    ("aggression", "침략"), ("agony", "고통"), ("alignment", "정렬"), ("allegation", "주장"),
    ("alleviate", "완화하다"), ("allocation", "배분"), ("allusion", "암시"), ("alteration", "변경"),
    ("ambiguity", "모호함"), ("amenity", "편의시설"), ("analogy", "유추"), ("anatomy", "해부학"),
    ("anecdote", "일화"), ("animated", "생동감 있는"), ("annex", "부속건물"), ("annotation", "주석"),
    ("anomaly", "변칙"), ("antagonist", "적대자"), ("anthropology", "인류학"), ("apparatus", "장치"),
    ("apparel", "의류"), ("applaud", "박수 치다"), ("appreciation", "감사"), ("apprentice", "견습생"),
    ("arbitrary", "임의의"), ("archaeology", "고고학"), ("archive", "기록 보관소"), ("ardent", "열렬한"),
    ("arena", "경기장"), ("articulate", "분명하게 말하다"), ("artifact", "유물"), ("ascertain", "확인하다"),
    ("aspiration", "열망"), ("assassination", "암살"), ("assurance", "보장"), ("astonish", "놀라게 하다"),
    ("astronomy", "천문학"), ("asylum", "피난처"), ("atrocity", "잔학행위"), ("attachment", "애착"),
    ("attain", "달성하다"), ("attic", "다락방"), ("attorney", "변호사"), ("authentic", "진짜의"),
    ("authorization", "허가"), ("autobiography", "자서전"), ("autonomy", "자치"), ("auxiliary", "보조의"),
    ("aversion", "혐오"), ("aviation", "항공"), ("backdrop", "배경"), ("backlash", "반발"),
    ("ballot", "투표용지"), ("bandwidth", "대역폭"), ("bankrupt", "파산한"), ("barbecue", "바비큐"),
    ("baroque", "바로크"), ("battalion", "대대"), ("beacon", "등대"), ("benevolent", "자비로운"),
    ("beverage", "음료"), ("bibliography", "참고문헌"), ("bilateral", "양자간의"), ("biography", "전기"),
    ("bizarre", "기괴한"), ("blossom", "꽃"), ("blunder", "실수"), ("boiler", "보일러"),
    ("bolster", "강화하다"), ("bonding", "유대감 형성"), ("booklet", "소책자"), ("botanical", "식물학의"),
    ("boulder", "바위"), ("boutique", "부티크"), ("bracelet", "팔찌"), ("breakdown", "고장"),
    ("bribe", "뇌물"), ("briefing", "브리핑"), ("brochure", "안내서"), ("broker", "중개인"),
    ("browse", "검색하다"), ("brutal", "잔인한"), ("bureaucratic", "관료적인"), ("burglary", "강도"),
    ("calamity", "재앙"), ("caliber", "구경"), ("calligraphy", "서예"), ("camouflage", "위장"),
    ("candid", "솔직한"), ("cannabis", "대마초"), ("canopy", "차양"), ("captive", "포로"),
    ("captivity", "감금"), ("carbohydrate", "탄수화물"), ("cardiovascular", "심혈관의"), ("caretaker", "관리인"),
    ("cascade", "폭포"), ("catalog", "목록"), ("catastrophic", "재앙적인"), ("cater", "제공하다"),
    ("cathedral", "대성당"), ("causation", "인과관계"), ("cavalry", "기병대"), ("cemetery", "묘지"),
    ("censorship", "검열"), ("centerpiece", "중심부"), ("centralize", "중앙 집권화하다"), ("ceramic", "도자기"),
    ("certification", "인증"), ("chancellor", "수상"), ("chant", "성가"), ("charisma", "카리스마"),
    ("charitable", "자선의"), ("checkpoint", "검문소"), ("cholesterol", "콜레스테롤"), ("choreography", "안무"),
    ("chronic", "만성적인"), ("chronological", "연대순의"), ("circulation", "순환"), ("citizenship", "시민권"),
    ("civic", "시민의"), ("clarity", "명확성"), ("classification", "분류"), ("clause", "조항"),
    ("clergy", "성직자"), ("cliche", "클리셰"), ("climax", "절정"), ("closure", "폐쇄"),
    ("coalition", "연합"), ("cognitive", "인지의"), ("coherent", "일관된"), ("coincide", "일치하다"),
    ("collaboration", "협업"), ("collective", "집단적인"), ("collision", "충돌"), ("colonial", "식민지의"),
    ("columnist", "칼럼니스트"), ("commemorate", "기념하다"), ("commentary", "해설"), ("commodity", "상품"),
    ("communal", "공동의"), ("compact", "소형의"), ("comparable", "비교할 만한"), ("compartment", "구획"),
    ("compassion", "연민"), ("compatible", "호환되는"), ("compel", "강요하다"), ("compensate", "보상하다"),
    ("competence", "능력"), ("compile", "편집하다"), ("complement", "보완하다"), ("complexity", "복잡성"),
    ("compliance", "준수"), ("compliment", "칭찬"), ("compose", "구성하다"), ("compound", "화합물"),
    ("comprehensive", "포괄적인"), ("comprise", "포함하다"), ("compromise", "타협"), ("compulsory", "의무적인"),
    ("concealment", "은폐"), ("conception", "개념"), ("concession", "양보"), ("conclusive", "결정적인"),
    ("concrete", "콘크리트"), ("concurrent", "동시의"), ("condemn", "비난하다"), ("condensation", "응축"),
    ("configuration", "구성"), ("confinement", "감금"), ("confirmation", "확인"), ("confiscate", "몰수하다"),
    ("confrontation", "대결"), ("congregation", "신도"), ("conjunction", "접속사"), ("consecutive", "연속적인"),
    ("consensus", "합의"), ("conservation", "보존"), ("consolidate", "통합하다"), ("conspiracy", "음모"),
    ("constituent", "구성요소"), ("constitution", "헌법"), ("constraint", "제약"), ("consultation", "상담"),
    ("contaminate", "오염시키다"), ("contemplate", "숙고하다"), ("contemporary", "현대의"), ("contempt", "경멸"),
    ("contention", "주장"), ("contingency", "우발사태"), ("contractor", "계약자"), ("contradiction", "모순"),
    ("contribute", "기여하다"), ("controversy", "논쟁"), ("conversion", "전환"), ("convey", "전달하다"),
    ("conviction", "확신"), ("coordinate", "조정하다"), ("copyright", "저작권"), ("cornerstone", "초석"),
    ("corporate", "기업의"), ("correlation", "상관관계"), ("correspond", "일치하다"), ("corridor", "복도"),
    ("corrupt", "부패한"), ("cosmetic", "화장품"), ("counsel", "조언"), ("counteract", "대응하다"),
    ("counterpart", "상대방"), ("coupon", "쿠폰"), ("courtesy", "예의"), ("coverage", "보도"),
    ("covert", "은밀한"), ("craft", "공예"), ("credibility", "신뢰성"), ("criterion", "기준"),
    ("critique", "비평"), ("crucial", "중요한"), ("culminate", "절정에 달하다"), ("cumulative", "누적의"),
    ("curator", "큐레이터"), ("curriculum", "교육과정"), ("custody", "양육권"), ("customize", "맞춤화하다"),
    ("cylinder", "실린더"), ("debris", "잔해"), ("debut", "데뷔"), ("deceive", "속이다"),
    ("declaration", "선언"), ("dedicate", "헌신하다"), ("deduction", "공제"), ("default", "기본값"),
    ("defect", "결함"), ("defiance", "반항"), ("deficiency", "결핍"), ("deficit", "적자"),
    ("degradation", "저하"), ("delegate", "대리인"), ("deliberate", "신중한"), ("demographic", "인구통계의"),
    ("denounce", "비난하다"), ("depict", "묘사하다"), ("deploy", "배치하다"), ("depreciate", "가치가 떨어지다"),
    ("deprive", "박탈하다"), ("derivative", "파생물"), ("descend", "내려가다"), ("designation", "지정"),
    ("deteriorate", "악화하다"), ("detrimental", "해로운"), ("devastate", "황폐화시키다"), ("deviation", "이탈"),
    ("devote", "헌신하다"), ("diagnose", "진단하다"), ("dialect", "방언"), ("dictate", "지시하다"),
    ("differentiate", "구별하다"), ("dilemma", "딜레마"), ("diminish", "줄이다"), ("diploma", "졸업장"),
    ("diplomatic", "외교적인"), ("directory", "디렉토리"), ("discard", "버리다"), ("discipline", "훈육"),
    ("disclose", "공개하다"), ("discourse", "담론"), ("discrete", "별개의"), ("discrimination", "차별"),
    ("dismay", "경악"), ("disperse", "흩뿌리다"), ("disposition", "기질"), ("disproportionate", "불균형한"),
    ("disrupt", "방해하다"), ("dissent", "이의"), ("dissolve", "녹이다"), ("distort", "왜곡하다"),
    ("distraction", "주의 산만"), ("diverse", "다양한"), ("dividend", "배당금"), ("doctrine", "교리"),
    ("documentation", "문서화"), ("domain", "영역"), ("donation", "기부"), ("dormitory", "기숙사"),
    ("dosage", "복용량"), ("download", "다운로드"), ("drastically", "급격히"), ("dreadful", "무서운"),
    ("drought", "가뭄"), ("duplicate", "복제하다"), ("duration", "기간"), ("dynamics", "역학"),
    ("dysfunction", "기능장애"), ("echo", "메아리"), ("ecological", "생태학적인"), ("ecosystem", "생태계"),
    ("editorial", "사설"), ("elaborate", "정교한"), ("electoral", "선거의"), ("elevation", "고도"),
    ("eligible", "자격이 있는"), ("eliminate", "제거하다"), ("eloquent", "웅변의"), ("embed", "심다"),
    ("embrace", "포용하다"), ("emergence", "출현"), ("emission", "배출"), ("empathy", "공감"),
    ("empirical", "경험적인"), ("empower", "권한을 부여하다"), ("enact", "제정하다"), ("encompass", "포함하다"),
    ("encounter", "만나다"), ("endeavor", "노력"), ("endorse", "지지하다"), ("enforcement", "시행"),
    ("engagement", "약혼"), ("enhance", "향상시키다"), ("enlighten", "계몽하다"), ("enrich", "풍요롭게 하다"),
    ("enrollment", "등록"), ("enterprise", "기업"), ("enthusiastic", "열정적인"), ("entitle", "자격을 주다"),
    ("entity", "실체"), ("entrepreneur", "기업가"), ("environmental", "환경의"), ("epidemic", "유행병"),
    ("episode", "에피소드"), ("equation", "방정식"), ("equilibrium", "균형"), ("equip", "장비하다"),
    ("equivalent", "동등한"), ("erode", "침식하다"), ("escalate", "확대되다"), ("essence", "본질"),
    ("establishment", "설립"), ("eternal", "영원한"), ("ethical", "윤리적인"), ("ethnic", "민족의"),
    ("evacuate", "대피하다"), ("evaluate", "평가하다"), ("eventual", "최종의"), ("evoke", "불러일으키다"),
    ("evolution", "진화"), ("exaggerate", "과장하다"), ("exceed", "초과하다"), ("exceptional", "예외적인"),
    ("excess", "초과"), ("exclusion", "제외"), ("execute", "실행하다"), ("exemplify", "예시하다"),
    ("exempt", "면제된"), ("exert", "가하다"), ("exhaust", "지치게 하다"), ("exile", "유배"),
    ("exotic", "이국적인"), ("expedition", "원정"), ("expenditure", "지출"), ("expertise", "전문지식"),
    ("explicit", "명시적인"), ("exploit", "착취하다"), ("exploration", "탐험"), ("expose", "노출하다"),
    ("exterior", "외부의"), ("extract", "추출하다"), ("extraordinary", "비범한"), ("extravagant", "사치스러운"),
    ("fabulous", "멋진"), ("facade", "정면"), ("facilitate", "촉진하다"), ("faction", "파벌"),
    ("faculty", "학부"), ("famine", "기근"), ("fascinate", "매혹하다"), ("fatal", "치명적인"),
    ("fatigue", "피로"), ("favorable", "유리한"), ("feasible", "실행 가능한"), ("federation", "연방"),
    ("feminist", "페미니스트"), ("fertility", "비옥함"), ("fiance", "약혼자"), ("fiber", "섬유"),
    ("fierce", "사나운"), ("financing", "자금조달"), ("fiscal", "재정의"), ("fixture", "설비"),
    ("flatter", "아첨하다"), ("flaw", "결점"), ("flexibility", "유연성"), ("flourish", "번성하다"),
    ("fluctuate", "변동하다"), ("fluid", "유체"), ("foe", "적"), ("folklore", "민속"),
    ("footage", "영상"), ("forecast", "예측"), ("foreground", "전경"), ("formidable", "가공할"),
    ("formulate", "공식화하다"), ("forthcoming", "다가오는"), ("fortify", "강화하다"), ("forum", "포럼"),
    ("fossil", "화석"), ("foster", "육성하다"), ("fraction", "분수"), ("fragment", "조각"),
    ("fragrant", "향기로운"), ("framework", "체계"), ("franchise", "프랜차이즈"), ("fraud", "사기"),
    ("freight", "화물"), ("frenzy", "광란"), ("frequency", "빈도"), ("fringe", "가장자리"),
    ("frustrate", "좌절시키다"), ("fulfill", "이행하다"), ("functional", "기능적인"), ("fundamental", "근본적인"),
]

# C1 레벨 (500개) - 축약
C1_WORDS = [
    ("aberration", "일탈"), ("abhor", "혐오하다"), ("abide", "따르다"), ("abnormality", "이상"),
    ("abolishment", "폐지"), ("abrasive", "거친"), ("abridge", "요약하다"), ("abscond", "도주하다"),
    ("abstain", "삼가다"), ("abstraction", "추상화"), ("abysmal", "심연의"), ("accede", "동의하다"),
    ("accentuate", "강조하다"), ("acclaim", "찬사"), ("acclimatize", "적응시키다"), ("accolade", "찬사"),
    ("accomplice", "공범"), ("accredit", "인가하다"), ("accrue", "발생하다"), ("accusatory", "비난하는"),
    ("acerbic", "신랄한"), ("acquiesce", "묵인하다"), ("acquittal", "무죄 선고"), ("acrimonious", "신랄한"),
    ("actualize", "실현하다"), ("adamant", "단호한"), ("addendum", "부록"), ("adept", "숙련된"),
    ("adherent", "지지자"), ("adjunct", "부속물"), ("admonish", "훈계하다"), ("adroit", "능숙한"),
    ("adulation", "아첨"), ("adversary", "적"), ("adversity", "역경"), ("affable", "상냥한"),
    ("affidavit", "선서 진술서"), ("affiliate", "계열사"), ("affinity", "친밀감"), ("affluent", "부유한"),
    ("aftermath", "여파"), ("aggravate", "악화시키다"), ("aggregate", "총계"), ("aghast", "아연실색한"),
    ("agile", "민첩한"), ("agonize", "고뇌하다"), ("agrarian", "농업의"), ("akin", "유사한"),
    ("albeit", "비록 ~일지라도"), ("alchemy", "연금술"), ("allegiance", "충성"), ("alleviation", "완화"),
    ("allot", "할당하다"), ("allude", "암시하다"), ("ally", "동맹국"), ("amalgamate", "합병하다"),
    ("ambivalent", "양면적인"), ("ameliorate", "개선하다"), ("amenable", "순응하는"), ("amicable", "우호적인"),
    ("amnesty", "사면"), ("amorphous", "무정형의"), ("amplify", "증폭하다"), ("anarchist", "무정부주의자"),
    ("anarchy", "무정부 상태"), ("anecdotal", "일화적인"), ("animosity", "적의"), ("annihilate", "전멸시키다"),
    ("anomalous", "이상한"), ("antagonize", "적대시하다"), ("antecedent", "선행사"), ("antidote", "해독제"),
    ("antiquated", "구식의"), ("antithesis", "정반대"), ("apathetic", "무관심한"), ("apex", "정점"),
    ("appease", "달래다"), ("apportion", "배분하다"), ("appraisal", "평가"), ("apprehend", "체포하다"),
    ("apprehensive", "불안한"), ("aptitude", "적성"), ("aquatic", "수중의"), ("arbitrary", "임의의"),
    ("arbitration", "중재"), ("archaic", "고대의"), ("archipelago", "군도"), ("arduous", "힘든"),
    ("aristocracy", "귀족"), ("armistice", "휴전"), ("arrogant", "오만한"), ("articulation", "명확한 표현"),
    ("ascend", "오르다"), ("ascetic", "금욕적인"), ("aspire", "열망하다"), ("assailant", "공격자"),
    ("assent", "동의"), ("assertion", "주장"), ("assiduous", "근면한"), ("assimilate", "동화시키다"),
    ("assuage", "완화하다"), ("astute", "빈틈없는"), ("atrocious", "잔학한"), ("atrophy", "위축"),
    ("attenuate", "약화시키다"), ("attest", "증명하다"), ("audacious", "대담한"), ("augment", "증가시키다"),
    ("auspicious", "길조의"), ("austere", "엄격한"), ("authenticate", "인증하다"), ("authoritarian", "권위주의적인"),
    ("avarice", "탐욕"), ("avert", "피하다"), ("avid", "열렬한"), ("axiom", "공리"),
    ("baleful", "해로운"), ("banal", "진부한"), ("bane", "골칫거리"), ("bask", "즐기다"),
    ("bedrock", "기반"), ("beguile", "속이다"), ("behold", "바라보다"), ("belabor", "장황하게 말하다"),
    ("beleaguered", "포위된"), ("belie", "보여주다"), ("belittle", "경시하다"), ("bellicose", "호전적인"),
    ("bemoan", "한탄하다"), ("benefactor", "후원자"), ("benign", "양성의"), ("bequeath", "물려주다"),
    ("berate", "꾸짖다"), ("bereft", "잃은"), ("besiege", "포위하다"), ("bestow", "수여하다"),
    ("betrothal", "약혼"), ("bewilder", "당혹케 하다"), ("bifurcate", "두 갈래로 나누다"), ("bigotry", "편협"),
    ("bilateral", "양자간의"), ("binge", "폭식"), ("bivouac", "야영하다"), ("bland", "부드러운"),
    ("blasphemy", "신성모독"), ("blatant", "노골적인"), ("bleak", "황량한"), ("blemish", "흠"),
    ("blight", "황폐시키다"), ("bliss", "지복"), ("blithe", "태평한"), ("blockade", "봉쇄"),
    ("bludgeon", "곤봉"), ("bluff", "허세"), ("blunder", "실수하다"), ("blunt", "무딘"),
    ("boisterous", "떠들썩한"), ("bolster", "지지하다"), ("bombastic", "과장된"), ("bona fide", "진정한"),
    ("bonanza", "횡재"), ("bondage", "속박"), ("boon", "혜택"), ("bootstrap", "자력으로"),
    ("bourgeois", "부르주아"), ("boycott", "보이콧"), ("brazen", "뻔뻔한"), ("breach", "위반"),
    ("brevity", "간결함"), ("brittle", "부서지기 쉬운"), ("brunt", "충격"), ("bucolic", "전원의"),
    ("buffet", "시련을 주다"), ("bulwark", "보루"), ("bumbling", "서투른"), ("bureaucrat", "관료"),
    ("burgeon", "급성장하다"), ("burlesque", "희화"), ("burnish", "닦다"), ("buttress", "지지하다"),
    ("bylaw", "정관"), ("byzantine", "복잡한"), ("cacophony", "불협화음"), ("cadence", "운율"),
    ("cajole", "구슬리다"), ("calamitous", "재앙적인"), ("calibrate", "조정하다"), ("callous", "무정한"),
    ("candor", "솔직함"), ("canonical", "정통의"), ("capacious", "넓은"), ("capitulate", "항복하다"),
    ("capricious", "변덕스러운"), ("cardinal", "기본적인"), ("caricature", "풍자화"), ("carnage", "대학살"),
    ("carnivore", "육식동물"), ("castigate", "비난하다"), ("catalyst", "촉매"), ("categorical", "단정적인"),
    ("catharsis", "카타르시스"), ("caucus", "간부회의"), ("caustic", "신랄한"), ("cavalier", "건방진"),
    ("caveat", "경고"), ("cede", "양도하다"), ("celestial", "천상의"), ("censor", "검열하다"),
    ("censure", "비난"), ("cerebral", "지적인"), ("cessation", "중단"), ("chagrin", "분함"),
    ("chameleon", "카멜레온"), ("champion", "옹호하다"), ("chaperone", "보호자"), ("charade", "가장"),
    ("charlatan", "사기꾼"), ("chasm", "깊은 틈"), ("chaste", "순결한"), ("chastise", "징계하다"),
    ("chicanery", "속임수"), ("chide", "꾸짖다"), ("chimera", "환상"), ("choleric", "성급한"),
    ("chronicle", "연대기"), ("cipher", "암호"), ("circuitous", "우회하는"), ("circumscribe", "제한하다"),
    ("circumspect", "신중한"), ("circumvent", "우회하다"), ("citadel", "성채"), ("clandestine", "비밀의"),
    ("clemency", "관용"), ("cloister", "수도원"), ("coalesce", "합치다"), ("coerce", "강요하다"),
    ("coffer", "금고"), ("cogent", "설득력 있는"), ("cognizant", "인식하는"), ("cohesion", "결속"),
    ("collateral", "담보"), ("colloquial", "구어체의"), ("collusion", "공모"), ("colossal", "거대한"),
    ("comely", "아름다운"), ("commensurate", "상응하는"), ("commiserate", "동정하다"), ("commodious", "넓은"),
    ("commute", "통근하다"), ("compelling", "설득력 있는"), ("compendium", "개요"), ("complacent", "자기만족적인"),
    ("compliant", "순응하는"), ("complicity", "공모"), ("composure", "평정"), ("compunction", "양심의 가책"),
    ("concatenate", "연결하다"), ("concede", "인정하다"), ("conceit", "자만"), ("concentric", "동심원의"),
    ("concerted", "협력적인"), ("concise", "간결한"), ("conclusive", "결정적인"), ("concoct", "조작하다"),
    ("concordance", "일치"), ("concur", "동의하다"), ("condescend", "겸손해지다"), ("conditional", "조건부의"),
    ("condolence", "조의"), ("condone", "용납하다"), ("conducive", "도움이 되는"), ("confluence", "합류"),
    ("confound", "당혹시키다"), ("congenial", "마음이 맞는"), ("conglomerate", "대기업"), ("conjecture", "추측"),
    ("conjure", "불러내다"), ("connive", "묵인하다"), ("connoisseur", "감정가"), ("connotation", "함축"),
    ("conscientious", "양심적인"), ("consecrate", "봉헌하다"), ("consign", "위탁하다"), ("consortium", "컨소시엄"),
    ("conspicuous", "눈에 띄는"), ("constrain", "강제하다"), ("constrict", "수축시키다"), ("consummate", "완성하다"),
    ("contiguous", "인접한"), ("contingent", "우연의"), ("contrite", "회개하는"), ("contrivance", "고안"),
    ("contrived", "부자연스러운"), ("conundrum", "수수께끼"), ("convene", "소집하다"), ("convergence", "수렴"),
    ("conversant", "정통한"), ("convict", "유죄 판결하다"), ("convivial", "쾌활한"), ("convoluted", "복잡한"),
    ("copious", "풍부한"), ("corollary", "결과"), ("corroborate", "확증하다"), ("corrode", "부식시키다"),
    ("countenance", "용모"), ("counterfeit", "위조품"), ("countermand", "취소하다"), ("covet", "탐내다"),
    ("crass", "둔감한"), ("credence", "신뢰"), ("creed", "신조"), ("crescendo", "점점 강해짐"),
    ("crevice", "틈"), ("cringe", "움츠리다"), ("cryptic", "불가사의한"), ("crystallize", "구체화하다"),
    ("culinary", "요리의"), ("culmination", "절정"), ("culpable", "유죄의"), ("culprit", "범인"),
    ("cumbersome", "성가신"), ("cumulative", "누적의"), ("cupidity", "탐욕"), ("curative", "치료의"),
    ("cursory", "대충하는"), ("curtail", "단축하다"), ("cynical", "냉소적인"), ("dais", "연단"),
    ("dalliance", "장난"), ("dapper", "말쑥한"), ("daunt", "위협하다"), ("dawdle", "빈둥거리다"),
    ("dearth", "부족"), ("debacle", "대실패"), ("debilitate", "약하게 하다"), ("decadent", "퇴폐적인"),
    ("decapitate", "참수하다"), ("decimate", "대량학살하다"), ("decipher", "해독하다"), ("decorum", "예절"),
    ("decoy", "미끼"), ("decree", "법령"), ("decrepit", "노후한"), ("decry", "비난하다"),
    ("deference", "경의"), ("defiant", "도전적인"), ("defile", "더럽히다"), ("deft", "솜씨 좋은"),
    ("defunct", "소멸한"), ("degenerate", "타락한"), ("degrading", "굴욕적인"), ("deign", "~하시다"),
    ("deject", "낙담시키다"), ("delectable", "맛있는"), ("deliberation", "숙고"), ("delineate", "묘사하다"),
    ("delinquent", "비행의"), ("delirious", "정신착란의"), ("deluge", "대홍수"), ("delusion", "망상"),
    ("demagogue", "선동가"), ("demeanor", "태도"), ("demise", "죽음"), ("demolish", "파괴하다"),
    ("demure", "얌전한"), ("denigrate", "비방하다"), ("denizen", "거주자"), ("denouncement", "비난"),
    ("denunciation", "비난"), ("deplete", "고갈시키다"), ("deplore", "개탄하다"), ("deploy", "배치하다"),
    ("depose", "퇴위시키다"), ("depraved", "타락한"), ("deprecate", "반대하다"), ("derelict", "유기된"),
    ("deride", "조롱하다"), ("derision", "조롱"), ("derivative", "파생적인"), ("derogatory", "경멸적인"),
    ("desecrate", "모독하다"), ("desist", "그만두다"), ("desolate", "황량한"), ("despicable", "비열한"),
    ("despot", "폭군"), ("destitute", "궁핍한"), ("desultory", "산만한"), ("detain", "구금하다"),
    ("deter", "단념시키다"), ("detract", "손상시키다"), ("deviant", "일탈한"), ("devious", "교활한"),
    ("devolve", "위임하다"), ("devout", "독실한"), ("dexterity", "솜씨"), ("diabolical", "악마같은"),
]

# C2 레벨 (500개) - 축약
C2_WORDS = [
    ("abeyance", "중단"), ("ablution", "목욕"), ("abnegate", "포기하다"), ("abominate", "혐오하다"),
    ("aborigine", "원주민"), ("abound", "풍부하다"), ("abrade", "마모시키다"), ("abrogate", "폐지하다"),
    ("abstemious", "절제하는"), ("accost", "말을 걸다"), ("accouterment", "장비"), ("acme", "정점"),
    ("acolyte", "시종"), ("acoustics", "음향학"), ("acquiesce", "묵인하다"), ("acrimonious", "신랄한"),
    ("actuarial", "보험계리의"), ("acuity", "예리함"), ("acumen", "통찰력"), ("adjudicate", "판결하다"),
    ("admonition", "훈계"), ("adumbrate", "예고하다"), ("aegis", "보호"), ("affectation", "가식"),
    ("affliction", "고통"), ("aggrandize", "확대하다"), ("alacrity", "기꺼이 함"), ("aleatory", "우연의"),
    ("algorithm", "알고리즘"), ("alienate", "소외시키다"), ("allegory", "우화"), ("alliteration", "두운"),
    ("amalgamation", "합병"), ("ambit", "범위"), ("ambivalence", "양면감정"), ("ambrosia", "신의 음식"),
    ("amelioration", "개선"), ("anachronism", "시대착오"), ("anathema", "저주"), ("ancillary", "보조의"),
    ("anguish", "고뇌"), ("animadversion", "비난"), ("annuity", "연금"), ("anomie", "무규범 상태"),
    ("antebellum", "전쟁 전의"), ("anthropomorphic", "의인화된"), ("antipathy", "반감"), ("apostate", "배교자"),
    ("apotheosis", "신격화"), ("appellation", "명칭"), ("apprise", "알리다"), ("approbation", "승인"),
    ("apropos", "적절한"), ("arabesque", "아라베스크"), ("arcane", "비밀의"), ("archetype", "원형"),
    ("ascertain", "확인하다"), ("ascribe", "~의 탓으로 돌리다"), ("aseptic", "무균의"), ("askance", "비스듬히"),
    ("asperity", "거침"), ("aspersion", "비방"), ("asseverate", "단언하다"), ("assuagement", "완화"),
    ("atavistic", "격세유전의"), ("attenuated", "약화된"), ("aureole", "후광"), ("auspice", "보호"),
    ("autodidact", "독학자"), ("avaunt", "물러서라"), ("avowal", "공언"), ("axiom", "공리"),
    ("bacchanal", "주신제"), ("badinage", "농담"), ("ballast", "밸러스트"), ("balsam", "발삼"),
    ("banality", "진부함"), ("baroque", "바로크의"), ("barrage", "집중포화"), ("bastion", "보루"),
    ("beatific", "지복의"), ("bedizen", "화려하게 꾸미다"), ("beholden", "은혜를 입은"), ("beneficent", "자비로운"),
    ("benighted", "무지한"), ("bequest", "유산"), ("berate", "꾸짖다"), ("bereft", "~을 잃은"),
    ("besmirch", "더럽히다"), ("bete noire", "골칫거리"), ("bifurcation", "분기"), ("blandishment", "감언"),
    ("blase", "싫증난"), ("blather", "지껄이다"), ("blighted", "황폐한"), ("bombast", "과장"),
    ("bonhomie", "쾌활함"), ("bowdlerize", "삭제하다"), ("braggadocio", "허풍"), ("bravado", "허세"),
    ("bricolage", "브리콜라주"), ("brogue", "사투리"), ("bromide", "진부한 표현"), ("bruit", "소문내다"),
    ("buccaneer", "해적"), ("buoyant", "쾌활한"), ("burgeoning", "급성장하는"), ("burnished", "빛나는"),
    ("cabal", "도당"), ("cadaverous", "시체 같은"), ("caesura", "휴지"), ("calumny", "중상"),
    ("canard", "거짓 이야기"), ("candor", "솔직함"), ("cant", "위선적 말"), ("cantankerous", "심술궂은"),
    ("capacitate", "능력을 주다"), ("caparison", "마의"), ("capitulation", "항복"), ("capriciousness", "변덕"),
    ("careen", "기울다"), ("carrion", "부패한 고기"), ("carte blanche", "백지위임"), ("cataclysm", "대변동"),
    ("catechism", "교리문답"), ("catholic", "보편적인"), ("celerity", "신속"), ("cerebration", "사고"),
    ("chagrin", "분함"), ("chameleon", "카멜레온"), ("charlatan", "사기꾼"), ("churlish", "무례한"),
    ("circuitous", "우회하는"), ("circumlocution", "완곡한 표현"), ("clairvoyant", "천리안의"), ("clamorous", "시끄러운"),
    ("cloistered", "은둔한"), ("cloying", "질리게 하는"), ("coagulate", "응고시키다"), ("codify", "성문화하다"),
    ("coeval", "동시대의"), ("cogitation", "숙고"), ("collate", "대조하다"), ("comestible", "식용의"),
    ("commencement", "시작"), ("commingle", "섞다"), ("compendious", "간결한"), ("comport", "행동하다"),
    ("concatenation", "연쇄"), ("conclave", "비밀회의"), ("concomitant", "수반하는"), ("concordat", "협정"),
    ("concupiscence", "정욕"), ("condign", "마땅한"), ("confabulation", "담화"), ("conflagration", "대화재"),
    ("conflation", "혼합"), ("conflux", "합류"), ("congeries", "집합"), ("congruence", "일치"),
    ("consanguinity", "혈연관계"), ("consequential", "중대한"), ("consternation", "경악"), ("consummate", "완벽한"),
    ("contravene", "위반하다"), ("contrition", "회개"), ("contumacious", "반항적인"), ("contumelious", "모욕적인"),
    ("convulsion", "경련"), ("copse", "작은 숲"), ("cornucopia", "풍요의 뿔"), ("corpulent", "뚱뚱한"),
    ("coruscate", "번쩍이다"), ("coterie", "동인"), ("cozen", "속이다"), ("crapulous", "폭음폭식의"),
    ("craven", "비겁한"), ("credulous", "잘 믿는"), ("crepuscular", "황혼의"), ("crestfallen", "풀이 죽은"),
    ("crucible", "도가니"), ("curmudgeon", "심술쟁이"), ("cynosure", "관심의 초점"), ("dalliance", "장난"),
    ("debauchery", "방탕"), ("debilitation", "쇠약"), ("declamation", "웅변"), ("declivity", "경사면"),
    ("decorous", "예의바른"), ("decrepitude", "노쇠"), ("delectation", "기쁨"), ("deleterious", "해로운"),
    ("delineation", "묘사"), ("deliquesce", "녹아 없어지다"), ("demarcation", "경계"), ("demijohn", "유리병"),
    ("demimonde", "사교계"), ("demonetize", "통화가치를 없애다"), ("denouement", "대단원"), ("depravity", "타락"),
    ("deprecation", "반대"), ("depredation", "약탈"), ("deracinate", "뿌리 뽑다"), ("deride", "조롱하다"),
    ("derivative", "파생적인"), ("descant", "이야기하다"), ("desideratum", "필수품"), ("despoil", "약탈하다"),
    ("despondent", "낙담한"), ("desuetude", "폐용"), ("desiccate", "건조시키다"), ("detritus", "잔해"),
    ("diaphanous", "투명한"), ("diatribe", "통렬한 비난"), ("dichotomy", "이분법"), ("didactic", "교훈적인"),
    ("diffidence", "자신감 부족"), ("dilatory", "꾸물거리는"), ("dilettante", "아마추어"), ("diminution", "감소"),
    ("dint", "힘"), ("dire", "극심한"), ("disabuse", "오해를 풀다"), ("disaffected", "불만을 품은"),
    ("disambiguate", "명확히 하다"), ("discernment", "통찰력"), ("discombobulate", "혼란시키다"), ("discomfiture", "당혹"),
    ("disconcert", "당혹시키다"), ("disconsolate", "슬픈"), ("discordant", "불협화음의"), ("discourse", "담론"),
    ("discursive", "산만한"), ("disenfranchise", "권리를 박탈하다"), ("disingenuous", "불성실한"), ("disinterested", "공평한"),
    ("disparage", "폄하하다"), ("disparate", "이질적인"), ("disparity", "불균형"), ("dispassionate", "냉정한"),
    ("dispensation", "면제"), ("dissemble", "숨기다"), ("disseminate", "퍼뜨리다"), ("dissension", "불화"),
    ("dissipate", "흩뜨리다"), ("dissolute", "방탕한"), ("dissonance", "불협화음"), ("dissuade", "말리다"),
    ("distend", "팽창시키다"), ("diurnal", "낮의"), ("divest", "박탈하다"), ("docile", "온순한"),
    ("doff", "벗다"), ("doggerel", "졸시"), ("doldrums", "우울"), ("dolorous", "슬픈"),
    ("dolt", "바보"), ("domicile", "주소"), ("dormant", "휴면의"), ("dotage", "노망"),
    ("doughty", "용감한"), ("dour", "엄한"), ("doyen", "원로"), ("draconian", "가혹한"),
    ("dross", "쓰레기"), ("dubious", "의심스러운"), ("ductile", "연성의"), ("dudgeon", "분개"),
    ("dulcet", "감미로운"), ("duress", "강압"), ("dyspeptic", "소화불량의"), ("ebullient", "열정적인"),
    ("eclectic", "절충적인"), ("eddy", "소용돌이"), ("edifice", "건물"), ("edification", "교화"),
    ("effacement", "소멸"), ("effervescent", "거품이 이는"), ("efficacious", "효과적인"), ("effrontery", "뻔뻔함"),
    ("effulgent", "빛나는"), ("effusion", "분출"), ("egalitarian", "평등주의의"), ("egregious", "지독한"),
    ("ejaculate", "외치다"), ("elation", "기쁨"), ("elocution", "웅변술"), ("elucidate", "설명하다"),
    ("elusive", "포착하기 어려운"), ("emaciate", "여위게 하다"), ("emanate", "발산하다"), ("embellish", "꾸미다"),
    ("emblazon", "장식하다"), ("embroil", "휘말리게 하다"), ("emendation", "수정"), ("emissary", "사절"),
    ("emollient", "완화제"), ("emolument", "보수"), ("empiricism", "경험주의"), ("emulate", "모방하다"),
    ("encomium", "찬사"), ("encroach", "침해하다"), ("endemic", "고유의"), ("enervate", "약화시키다"),
    ("enfranchise", "참정권을 주다"), ("engender", "낳다"), ("enigmatic", "수수께끼 같은"), ("enjoin", "명하다"),
    ("ennui", "권태"), ("enormity", "극악무도"), ("ensconced", "자리잡은"), ("enthrall", "매혹하다"),
    ("entreat", "간청하다"), ("enumerate", "열거하다"), ("enunciate", "발음하다"), ("ephemeral", "덧없는"),
    ("epicurean", "쾌락주의의"), ("epigram", "경구"), ("epistemology", "인식론"), ("epithet", "별명"),
    ("epitome", "전형"), ("equanimity", "평정"), ("equinox", "분점"), ("equitable", "공정한"),
    ("equivocate", "얼버무리다"), ("eradicate", "근절하다"), ("erstwhile", "이전의"), ("erudite", "박식한"),
    ("eschew", "피하다"), ("esoteric", "비밀의"), ("espouse", "지지하다"), ("ethereal", "천상의"),
    ("etymology", "어원"), ("eulogy", "찬사"), ("euphemism", "완곡어법"), ("euphoria", "행복감"),
    ("evanescent", "덧없는"), ("eviscerate", "내장을 빼다"), ("exacerbate", "악화시키다"), ("exacting", "까다로운"),
    ("exalt", "높이다"), ("exasperate", "화나게 하다"), ("excise", "세금"), ("excoriate", "비난하다"),
    ("exculpate", "무죄로 하다"), ("execrable", "가증스러운"), ("exegesis", "주석"), ("exemplar", "모범"),
    ("exhort", "권고하다"), ("exigent", "긴박한"), ("existential", "실존의"), ("exonerate", "무죄로 하다"),
    ("exorbitant", "터무니없는"), ("expatiate", "상술하다"), ("expatriate", "국외 거주자"), ("expedient", "편리한"),
    ("expedite", "촉진하다"), ("expiate", "속죄하다"), ("explicate", "설명하다"), ("expound", "설명하다"),
    ("expropriate", "몰수하다"), ("expunge", "삭제하다"), ("expurgate", "삭제하다"), ("extant", "현존하는"),
    ("extemporaneous", "즉흥의"), ("extenuate", "경감하다"), ("extirpate", "근절하다"), ("extol", "칭찬하다"),
    ("extraneous", "관계없는"), ("extrapolate", "추론하다"), ("extricate", "구해내다"), ("extrinsic", "외래의"),
    ("exuberant", "열정적인"), ("exude", "발산하다"), ("facetious", "익살스러운"), ("facile", "용이한"),
    ("facsimile", "사본"), ("factious", "분파적인"), ("fallacious", "그릇된"), ("fallow", "묵히는"),
    ("fastidious", "까다로운"), ("fatuous", "어리석은"), ("fawn", "아첨하다"), ("fealty", "충성"),
    ("feasance", "이행"), ("feckless", "무책임한"), ("fecund", "다산의"), ("feign", "가장하다"),
    ("felicitous", "적절한"), ("felon", "중죄인"), ("ferment", "발효시키다"), ("ferret", "뒤지다"),
    ("fervent", "열렬한"), ("fervid", "열정적인"), ("festoon", "꽃줄"), ("fetid", "악취 나는"),
    ("fetter", "족쇄"), ("fiasco", "대실패"), ("fiat", "명령"), ("fidelity", "충실함"),
    ("figment", "허구"), ("filial", "자녀의"), ("filibuster", "의사진행 방해"), ("finesse", "솜씨"),
    ("flaccid", "연약한"), ("flag", "시들다"), ("flagrant", "극악한"), ("flamboyant", "화려한"),
    ("fledgling", "초보자"), ("flippant", "경솔한"), ("florid", "화려한"), ("flotsam", "표류물"),
    ("flourish", "번영하다"), ("flout", "비웃다"), ("fluctuation", "변동"), ("fluency", "유창함"),
]

def create_word_entry(word: str, meaning: str, level: str, pos: str = "unknown") -> dict:
    return {
        "word": word,
        "meaning_ko": meaning,
        "level": level,
        "part_of_speech": pos,
        "source": "generated"
    }

def main():
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    all_words = []

    # A1 레벨
    for word, meaning in A1_WORDS:
        all_words.append(create_word_entry(word, meaning, "A1"))

    # A2 레벨
    for word, meaning in A2_WORDS:
        all_words.append(create_word_entry(word, meaning, "A2"))

    # B1 레벨
    for word, meaning in B1_WORDS:
        all_words.append(create_word_entry(word, meaning, "B1"))

    # B2 레벨
    for word, meaning in B2_WORDS:
        all_words.append(create_word_entry(word, meaning, "B2"))

    # C1 레벨
    for word, meaning in C1_WORDS:
        all_words.append(create_word_entry(word, meaning, "C1"))

    # C2 레벨
    for word, meaning in C2_WORDS:
        all_words.append(create_word_entry(word, meaning, "C2"))

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(all_words, f, ensure_ascii=False, indent=2)

    print(f"총 {len(all_words)}개 단어 생성 완료")
    print(f"저장: {OUTPUT_FILE}")

    # 레벨별 통계
    levels = {}
    for w in all_words:
        lvl = w["level"]
        levels[lvl] = levels.get(lvl, 0) + 1

    print("\n레벨별 단어 수:")
    for lvl in sorted(levels.keys()):
        print(f"  {lvl}: {levels[lvl]}")

if __name__ == "__main__":
    main()
