"""
대량 예문 데이터 생성
목표: 2000+ 예문
"""

import json
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "collected" / "sentences"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# 카테고리별 예문 (각 200-300개)
SENTENCES_BY_CATEGORY = {
    "greeting": [
        {"en": "Hello, how are you?", "ko": "안녕하세요, 어떻게 지내세요?", "level": "A1"},
        {"en": "Good morning!", "ko": "좋은 아침이에요!", "level": "A1"},
        {"en": "Good afternoon!", "ko": "좋은 오후에요!", "level": "A1"},
        {"en": "Good evening!", "ko": "좋은 저녁이에요!", "level": "A1"},
        {"en": "Good night!", "ko": "안녕히 주무세요!", "level": "A1"},
        {"en": "Nice to meet you.", "ko": "만나서 반가워요.", "level": "A1"},
        {"en": "How have you been?", "ko": "그동안 어떻게 지냈어요?", "level": "A2"},
        {"en": "It's been a while.", "ko": "오랜만이에요.", "level": "A2"},
        {"en": "Long time no see!", "ko": "오랜만이에요!", "level": "A2"},
        {"en": "What's up?", "ko": "뭐해?", "level": "A2"},
        {"en": "How's it going?", "ko": "어떻게 지내?", "level": "A2"},
        {"en": "I'm doing well, thanks.", "ko": "잘 지내요, 감사합니다.", "level": "A1"},
        {"en": "I'm fine, thank you.", "ko": "괜찮아요, 감사합니다.", "level": "A1"},
        {"en": "Not bad.", "ko": "나쁘지 않아요.", "level": "A2"},
        {"en": "Could be better.", "ko": "더 좋을 수도 있어요.", "level": "B1"},
        {"en": "I've been busy lately.", "ko": "요즘 바빴어요.", "level": "A2"},
        {"en": "Same as usual.", "ko": "평소와 같아요.", "level": "A2"},
        {"en": "Pleased to meet you.", "ko": "만나서 기쁩니다.", "level": "A2"},
        {"en": "The pleasure is mine.", "ko": "저도 기쁩니다.", "level": "B1"},
        {"en": "I've heard a lot about you.", "ko": "많이 들었습니다.", "level": "B1"},
        {"en": "See you later!", "ko": "나중에 봐요!", "level": "A1"},
        {"en": "Take care!", "ko": "잘 지내요!", "level": "A1"},
        {"en": "Have a nice day!", "ko": "좋은 하루 보내세요!", "level": "A1"},
        {"en": "See you tomorrow!", "ko": "내일 봐요!", "level": "A1"},
        {"en": "Keep in touch!", "ko": "연락해요!", "level": "A2"},
        {"en": "Let's catch up soon.", "ko": "곧 만나서 얘기해요.", "level": "B1"},
        {"en": "It was nice talking to you.", "ko": "얘기 나눠서 좋았어요.", "level": "A2"},
        {"en": "I look forward to seeing you again.", "ko": "다시 뵙기를 기대합니다.", "level": "B1"},
        {"en": "Give my regards to your family.", "ko": "가족분들께 안부 전해주세요.", "level": "B1"},
        {"en": "Say hi to everyone for me.", "ko": "모두에게 안부 전해줘.", "level": "A2"},
    ],

    "daily_conversation": [
        {"en": "What time is it?", "ko": "몇 시예요?", "level": "A1"},
        {"en": "It's 3 o'clock.", "ko": "3시예요.", "level": "A1"},
        {"en": "What day is it today?", "ko": "오늘 무슨 요일이에요?", "level": "A1"},
        {"en": "Today is Monday.", "ko": "오늘은 월요일이에요.", "level": "A1"},
        {"en": "What's the date today?", "ko": "오늘 몇일이에요?", "level": "A1"},
        {"en": "What's the weather like?", "ko": "날씨가 어때요?", "level": "A1"},
        {"en": "It's sunny today.", "ko": "오늘 화창해요.", "level": "A1"},
        {"en": "It looks like rain.", "ko": "비가 올 것 같아요.", "level": "A2"},
        {"en": "It's getting cold.", "ko": "추워지고 있어요.", "level": "A2"},
        {"en": "I'm hungry.", "ko": "배고파요.", "level": "A1"},
        {"en": "I'm thirsty.", "ko": "목말라요.", "level": "A1"},
        {"en": "I'm tired.", "ko": "피곤해요.", "level": "A1"},
        {"en": "I'm sleepy.", "ko": "졸려요.", "level": "A1"},
        {"en": "I'm bored.", "ko": "지루해요.", "level": "A1"},
        {"en": "I need to rest.", "ko": "쉬어야 해요.", "level": "A1"},
        {"en": "Let's take a break.", "ko": "쉬어요.", "level": "A2"},
        {"en": "What are you doing?", "ko": "뭐해요?", "level": "A1"},
        {"en": "I'm watching TV.", "ko": "TV 보고 있어요.", "level": "A1"},
        {"en": "I'm reading a book.", "ko": "책 읽고 있어요.", "level": "A1"},
        {"en": "I'm listening to music.", "ko": "음악 듣고 있어요.", "level": "A1"},
        {"en": "I'm working from home.", "ko": "재택근무 중이에요.", "level": "A2"},
        {"en": "I have plans tonight.", "ko": "오늘 밤에 약속 있어요.", "level": "A2"},
        {"en": "I'm free this weekend.", "ko": "이번 주말에 시간 있어요.", "level": "A2"},
        {"en": "Do you have any plans?", "ko": "계획 있어요?", "level": "A2"},
        {"en": "What do you usually do on weekends?", "ko": "주말에 보통 뭐 해요?", "level": "A2"},
        {"en": "I usually sleep in on Sundays.", "ko": "일요일에 보통 늦잠 자요.", "level": "A2"},
        {"en": "I like to relax at home.", "ko": "집에서 쉬는 게 좋아요.", "level": "A2"},
        {"en": "I enjoy going for walks.", "ko": "산책하는 것을 좋아해요.", "level": "A2"},
        {"en": "I prefer staying indoors.", "ko": "실내에 있는 게 좋아요.", "level": "B1"},
        {"en": "I need to do laundry.", "ko": "빨래해야 해요.", "level": "A2"},
        {"en": "I have to clean my room.", "ko": "방 청소해야 해요.", "level": "A2"},
        {"en": "Could you help me with this?", "ko": "이것 좀 도와줄래요?", "level": "A2"},
        {"en": "Sure, no problem.", "ko": "네, 문제없어요.", "level": "A2"},
        {"en": "I appreciate your help.", "ko": "도움 감사해요.", "level": "A2"},
        {"en": "Don't mention it.", "ko": "별말씀을요.", "level": "A2"},
    ],

    "cafe_restaurant": [
        {"en": "I'd like a coffee, please.", "ko": "커피 한 잔 주세요.", "level": "A1"},
        {"en": "Can I have an americano?", "ko": "아메리카노 주시겠어요?", "level": "A1"},
        {"en": "What would you recommend?", "ko": "뭘 추천하세요?", "level": "A2"},
        {"en": "What's your specialty?", "ko": "시그니처 메뉴가 뭐예요?", "level": "A2"},
        {"en": "Is it hot or iced?", "ko": "뜨거운 건가요 아이스인가요?", "level": "A1"},
        {"en": "I'll have it iced.", "ko": "아이스로 할게요.", "level": "A1"},
        {"en": "For here or to go?", "ko": "여기서 드실 건가요 포장인가요?", "level": "A1"},
        {"en": "To go, please.", "ko": "포장이요.", "level": "A1"},
        {"en": "Can I get this without sugar?", "ko": "설탕 빼고 주실 수 있나요?", "level": "A2"},
        {"en": "Could you make it less sweet?", "ko": "덜 달게 해주시겠어요?", "level": "A2"},
        {"en": "Do you have oat milk?", "ko": "오트밀크 있나요?", "level": "A2"},
        {"en": "What sizes do you have?", "ko": "사이즈 어떤 게 있나요?", "level": "A2"},
        {"en": "I'll take the large one.", "ko": "큰 걸로 할게요.", "level": "A1"},
        {"en": "How much is it?", "ko": "얼마예요?", "level": "A1"},
        {"en": "I'll pay by card.", "ko": "카드로 계산할게요.", "level": "A1"},
        {"en": "Can I pay with Apple Pay?", "ko": "애플페이로 결제할 수 있나요?", "level": "A2"},
        {"en": "Do you have Wi-Fi here?", "ko": "여기 와이파이 있나요?", "level": "A1"},
        {"en": "What's the Wi-Fi password?", "ko": "와이파이 비밀번호가 뭐예요?", "level": "A1"},
        {"en": "Is there an outlet nearby?", "ko": "근처에 콘센트 있나요?", "level": "A2"},
        {"en": "Can I get a refill?", "ko": "리필 해주시겠어요?", "level": "A2"},
        {"en": "A table for two, please.", "ko": "두 명이요.", "level": "A1"},
        {"en": "Do you have a reservation?", "ko": "예약하셨나요?", "level": "A2"},
        {"en": "I made a reservation for 7pm.", "ko": "7시에 예약했어요.", "level": "A2"},
        {"en": "Could we have the menu, please?", "ko": "메뉴판 주시겠어요?", "level": "A2"},
        {"en": "What do you have for vegetarians?", "ko": "채식주의자 메뉴 있나요?", "level": "B1"},
        {"en": "I'm allergic to nuts.", "ko": "견과류 알레르기가 있어요.", "level": "A2"},
        {"en": "Does this contain gluten?", "ko": "글루텐이 들어있나요?", "level": "B1"},
        {"en": "I'll have the steak.", "ko": "스테이크로 할게요.", "level": "A2"},
        {"en": "How would you like it cooked?", "ko": "어떻게 익혀드릴까요?", "level": "A2"},
        {"en": "Medium rare, please.", "ko": "미디엄 레어로요.", "level": "A2"},
        {"en": "Could I have some water?", "ko": "물 좀 주시겠어요?", "level": "A1"},
        {"en": "This is delicious!", "ko": "맛있어요!", "level": "A1"},
        {"en": "Could I have the bill, please?", "ko": "계산서 주시겠어요?", "level": "A2"},
        {"en": "We'd like to split the bill.", "ko": "따로 계산할게요.", "level": "A2"},
        {"en": "Is service charge included?", "ko": "서비스 비용이 포함되어 있나요?", "level": "B1"},
        {"en": "Keep the change.", "ko": "잔돈은 됐어요.", "level": "A2"},
    ],

    "shopping": [
        {"en": "I'm just looking, thanks.", "ko": "그냥 구경하는 거예요, 감사합니다.", "level": "A1"},
        {"en": "Can I help you find something?", "ko": "뭐 찾는 거 도와드릴까요?", "level": "A2"},
        {"en": "I'm looking for a jacket.", "ko": "재킷을 찾고 있어요.", "level": "A2"},
        {"en": "Do you have this in a different size?", "ko": "다른 사이즈 있나요?", "level": "A2"},
        {"en": "What size do you need?", "ko": "어떤 사이즈가 필요하세요?", "level": "A2"},
        {"en": "I wear a medium.", "ko": "미디엄 사이즈 입어요.", "level": "A2"},
        {"en": "Do you have this in black?", "ko": "검정색 있나요?", "level": "A2"},
        {"en": "Can I try this on?", "ko": "이거 입어봐도 될까요?", "level": "A2"},
        {"en": "Where's the fitting room?", "ko": "탈의실 어디예요?", "level": "A2"},
        {"en": "It doesn't fit.", "ko": "안 맞아요.", "level": "A2"},
        {"en": "It's too tight.", "ko": "너무 꽉 껴요.", "level": "A2"},
        {"en": "It's too loose.", "ko": "너무 헐렁해요.", "level": "A2"},
        {"en": "This fits perfectly.", "ko": "딱 맞아요.", "level": "A2"},
        {"en": "How much is this?", "ko": "이거 얼마예요?", "level": "A1"},
        {"en": "It's on sale.", "ko": "세일 중이에요.", "level": "A2"},
        {"en": "Is there a discount?", "ko": "할인 있나요?", "level": "A2"},
        {"en": "Can I get a better price?", "ko": "더 싸게 해주실 수 있나요?", "level": "B1"},
        {"en": "Do you accept credit cards?", "ko": "카드 받으세요?", "level": "A2"},
        {"en": "I'll take it.", "ko": "이걸로 할게요.", "level": "A2"},
        {"en": "Could I get a receipt?", "ko": "영수증 주시겠어요?", "level": "A2"},
        {"en": "Can I return this?", "ko": "이거 반품할 수 있나요?", "level": "A2"},
        {"en": "I'd like to exchange this.", "ko": "이거 교환하고 싶어요.", "level": "A2"},
        {"en": "I have a gift receipt.", "ko": "선물 영수증 있어요.", "level": "B1"},
        {"en": "Is there a warranty?", "ko": "보증서 있나요?", "level": "B1"},
        {"en": "Could you gift wrap this?", "ko": "선물 포장 해주시겠어요?", "level": "A2"},
        {"en": "Where can I find electronics?", "ko": "전자제품 어디 있나요?", "level": "A2"},
        {"en": "Is this available online?", "ko": "온라인에서 살 수 있나요?", "level": "B1"},
        {"en": "When will it be back in stock?", "ko": "언제 재입고 되나요?", "level": "B1"},
        {"en": "I'm looking for something cheaper.", "ko": "더 저렴한 거 찾고 있어요.", "level": "A2"},
        {"en": "This is out of my budget.", "ko": "예산 초과예요.", "level": "B1"},
    ],

    "transportation": [
        {"en": "Where's the nearest subway station?", "ko": "가장 가까운 지하철역이 어디예요?", "level": "A2"},
        {"en": "How do I get to the airport?", "ko": "공항에 어떻게 가요?", "level": "A2"},
        {"en": "Which line should I take?", "ko": "몇 호선 타야 해요?", "level": "A2"},
        {"en": "Where should I transfer?", "ko": "어디서 환승해야 해요?", "level": "A2"},
        {"en": "How many stops is it?", "ko": "몇 정거장이에요?", "level": "A2"},
        {"en": "Is this the right platform?", "ko": "여기가 맞는 승강장인가요?", "level": "A2"},
        {"en": "Does this train go to City Hall?", "ko": "이 기차 시청 가나요?", "level": "A2"},
        {"en": "What time is the next train?", "ko": "다음 기차 몇 시예요?", "level": "A2"},
        {"en": "The train is delayed.", "ko": "기차가 연착됐어요.", "level": "A2"},
        {"en": "I missed my train.", "ko": "기차 놓쳤어요.", "level": "A2"},
        {"en": "One ticket to Seoul, please.", "ko": "서울행 표 한 장 주세요.", "level": "A2"},
        {"en": "Round trip or one way?", "ko": "왕복이요 편도요?", "level": "A2"},
        {"en": "I need a round trip ticket.", "ko": "왕복 표 필요해요.", "level": "A2"},
        {"en": "Can I book a seat online?", "ko": "온라인으로 좌석 예매할 수 있나요?", "level": "B1"},
        {"en": "I'd like a window seat.", "ko": "창가 좌석으로 해주세요.", "level": "A2"},
        {"en": "Where can I catch a taxi?", "ko": "택시 어디서 타요?", "level": "A2"},
        {"en": "To the hotel, please.", "ko": "호텔로 가주세요.", "level": "A1"},
        {"en": "Can you take me to this address?", "ko": "이 주소로 가주시겠어요?", "level": "A2"},
        {"en": "How long will it take?", "ko": "얼마나 걸려요?", "level": "A2"},
        {"en": "Is there a lot of traffic?", "ko": "차가 많이 막히나요?", "level": "A2"},
        {"en": "Please drop me off here.", "ko": "여기서 내려주세요.", "level": "A2"},
        {"en": "Please use the meter.", "ko": "미터기 사용해주세요.", "level": "A2"},
        {"en": "Keep the change.", "ko": "잔돈은 가지세요.", "level": "A2"},
        {"en": "Can I rent a car?", "ko": "차 빌릴 수 있나요?", "level": "A2"},
        {"en": "I need a GPS.", "ko": "GPS 필요해요.", "level": "A2"},
        {"en": "Where do I return the car?", "ko": "어디서 차 반납해요?", "level": "A2"},
        {"en": "Is parking included?", "ko": "주차비 포함인가요?", "level": "B1"},
        {"en": "Where can I park?", "ko": "어디에 주차할 수 있나요?", "level": "A2"},
        {"en": "Is there free parking?", "ko": "무료 주차 있나요?", "level": "A2"},
        {"en": "I need to fill up the tank.", "ko": "기름 넣어야 해요.", "level": "A2"},
    ],

    "hotel": [
        {"en": "I have a reservation.", "ko": "예약했어요.", "level": "A2"},
        {"en": "I'd like to check in.", "ko": "체크인 하고 싶어요.", "level": "A2"},
        {"en": "Here's my booking confirmation.", "ko": "예약 확인서예요.", "level": "A2"},
        {"en": "May I see your passport?", "ko": "여권 보여주시겠어요?", "level": "A2"},
        {"en": "How many nights are you staying?", "ko": "몇 박 하시나요?", "level": "A2"},
        {"en": "I'm staying for three nights.", "ko": "3박 해요.", "level": "A2"},
        {"en": "What time is check-out?", "ko": "체크아웃 몇 시예요?", "level": "A2"},
        {"en": "Can I have a late check-out?", "ko": "레이트 체크아웃 가능한가요?", "level": "B1"},
        {"en": "Is breakfast included?", "ko": "조식 포함인가요?", "level": "A2"},
        {"en": "What time is breakfast?", "ko": "조식 몇 시예요?", "level": "A2"},
        {"en": "Where's the restaurant?", "ko": "레스토랑 어디예요?", "level": "A2"},
        {"en": "Is there a gym?", "ko": "헬스장 있나요?", "level": "A2"},
        {"en": "What's the WiFi password?", "ko": "와이파이 비밀번호가 뭐예요?", "level": "A2"},
        {"en": "The AC isn't working.", "ko": "에어컨이 안 돼요.", "level": "A2"},
        {"en": "Could I get extra towels?", "ko": "수건 더 주시겠어요?", "level": "A2"},
        {"en": "I need a wake-up call at 7am.", "ko": "7시에 모닝콜 부탁해요.", "level": "A2"},
        {"en": "Can I extend my stay?", "ko": "연박 가능한가요?", "level": "B1"},
        {"en": "Is there a safe in the room?", "ko": "방에 금고 있나요?", "level": "B1"},
        {"en": "Could you call a taxi for me?", "ko": "택시 불러주시겠어요?", "level": "A2"},
        {"en": "Where can I leave my luggage?", "ko": "짐 어디에 맡겨요?", "level": "A2"},
        {"en": "I'd like to check out.", "ko": "체크아웃 할게요.", "level": "A2"},
        {"en": "Can I pay with credit card?", "ko": "카드로 결제할 수 있나요?", "level": "A2"},
        {"en": "The room is too noisy.", "ko": "방이 너무 시끄러워요.", "level": "A2"},
        {"en": "Can I change rooms?", "ko": "방 바꿀 수 있나요?", "level": "A2"},
        {"en": "I locked myself out.", "ko": "방에 열쇠 두고 나왔어요.", "level": "B1"},
        {"en": "Is there room service?", "ko": "룸서비스 있나요?", "level": "A2"},
        {"en": "Can you recommend a restaurant nearby?", "ko": "근처 레스토랑 추천해주시겠어요?", "level": "B1"},
        {"en": "What's included in the minibar?", "ko": "미니바에 뭐가 있나요?", "level": "B1"},
        {"en": "I'd like to request housekeeping.", "ko": "청소 부탁드려요.", "level": "B1"},
        {"en": "Please put the 'Do Not Disturb' sign.", "ko": "방해하지 마세요 표시 달아주세요.", "level": "B1"},
    ],

    "airport": [
        {"en": "Where's the check-in counter?", "ko": "체크인 카운터 어디예요?", "level": "A2"},
        {"en": "I'd like to check in for my flight.", "ko": "체크인 하고 싶어요.", "level": "A2"},
        {"en": "Here's my passport and booking.", "ko": "여권과 예약 확인서예요.", "level": "A2"},
        {"en": "How many bags can I check?", "ko": "짐 몇 개까지 부칠 수 있나요?", "level": "A2"},
        {"en": "Is there a weight limit?", "ko": "무게 제한 있나요?", "level": "A2"},
        {"en": "Your bag is overweight.", "ko": "가방이 무게 초과예요.", "level": "B1"},
        {"en": "Can I have a window seat?", "ko": "창가 좌석으로 해주세요.", "level": "A2"},
        {"en": "I'd prefer an aisle seat.", "ko": "복도쪽 좌석이 좋아요.", "level": "A2"},
        {"en": "Is the flight on time?", "ko": "비행기 정시 출발인가요?", "level": "A2"},
        {"en": "The flight is delayed.", "ko": "비행기가 연착됐어요.", "level": "A2"},
        {"en": "What gate do I go to?", "ko": "몇 번 게이트로 가야 해요?", "level": "A2"},
        {"en": "Boarding starts at 10:30.", "ko": "탑승은 10시 30분에 시작해요.", "level": "A2"},
        {"en": "Where's the security check?", "ko": "보안검색대 어디예요?", "level": "A2"},
        {"en": "Please remove your laptop.", "ko": "노트북 꺼내주세요.", "level": "A2"},
        {"en": "Take off your belt and shoes.", "ko": "벨트와 신발 벗어주세요.", "level": "A2"},
        {"en": "Where's the duty-free shop?", "ko": "면세점 어디예요?", "level": "A2"},
        {"en": "Is this my connecting flight?", "ko": "이게 환승편인가요?", "level": "B1"},
        {"en": "Where do I collect my luggage?", "ko": "짐 어디서 찾아요?", "level": "A2"},
        {"en": "My luggage is missing.", "ko": "제 짐이 없어요.", "level": "A2"},
        {"en": "I need to file a lost baggage claim.", "ko": "분실 수하물 신고해야 해요.", "level": "B1"},
        {"en": "Where's the immigration counter?", "ko": "입국심사대 어디예요?", "level": "B1"},
        {"en": "What's the purpose of your visit?", "ko": "방문 목적이 뭔가요?", "level": "B1"},
        {"en": "I'm here on business.", "ko": "출장으로 왔어요.", "level": "A2"},
        {"en": "I'm here for vacation.", "ko": "휴가로 왔어요.", "level": "A2"},
        {"en": "How long will you be staying?", "ko": "얼마나 머무르실 건가요?", "level": "A2"},
        {"en": "I'll be here for one week.", "ko": "일주일 있을 거예요.", "level": "A2"},
        {"en": "Do you have anything to declare?", "ko": "신고할 물품 있으신가요?", "level": "B1"},
        {"en": "Nothing to declare.", "ko": "신고할 게 없어요.", "level": "A2"},
        {"en": "Where can I exchange money?", "ko": "환전 어디서 해요?", "level": "A2"},
        {"en": "Is there an ATM nearby?", "ko": "근처에 ATM 있나요?", "level": "A2"},
    ],

    "business": [
        {"en": "Nice to meet you.", "ko": "만나서 반갑습니다.", "level": "A1"},
        {"en": "Here's my business card.", "ko": "제 명함입니다.", "level": "A2"},
        {"en": "What company do you work for?", "ko": "어느 회사에서 일하세요?", "level": "A2"},
        {"en": "I work for Samsung.", "ko": "삼성에서 일해요.", "level": "A2"},
        {"en": "What do you do?", "ko": "무슨 일 하세요?", "level": "A2"},
        {"en": "I'm a software engineer.", "ko": "소프트웨어 엔지니어예요.", "level": "A2"},
        {"en": "I'm in marketing.", "ko": "마케팅 일을 해요.", "level": "A2"},
        {"en": "I manage a team of five.", "ko": "5명 팀을 관리해요.", "level": "B1"},
        {"en": "I've been with the company for 3 years.", "ko": "회사에 3년 있었어요.", "level": "B1"},
        {"en": "Shall we get started?", "ko": "시작할까요?", "level": "A2"},
        {"en": "Let's begin with the agenda.", "ko": "의제부터 시작하죠.", "level": "B1"},
        {"en": "As I mentioned earlier...", "ko": "앞서 말씀드렸듯이...", "level": "B1"},
        {"en": "Could you elaborate on that?", "ko": "좀 더 설명해 주시겠어요?", "level": "B1"},
        {"en": "I'd like to add something.", "ko": "덧붙이고 싶은 게 있어요.", "level": "B1"},
        {"en": "That's a good point.", "ko": "좋은 지적이에요.", "level": "A2"},
        {"en": "I agree with you.", "ko": "동의해요.", "level": "A2"},
        {"en": "I'm not sure I agree.", "ko": "동의하지 않아요.", "level": "B1"},
        {"en": "Let me think about it.", "ko": "생각해 볼게요.", "level": "A2"},
        {"en": "Can we schedule a meeting?", "ko": "미팅 잡을 수 있을까요?", "level": "B1"},
        {"en": "When are you available?", "ko": "언제 시간 되세요?", "level": "A2"},
        {"en": "How about next Tuesday?", "ko": "다음 주 화요일 어때요?", "level": "A2"},
        {"en": "Let me check my calendar.", "ko": "일정 확인해 볼게요.", "level": "A2"},
        {"en": "I have a conflict at that time.", "ko": "그 시간에 일정이 있어요.", "level": "B1"},
        {"en": "Can we reschedule?", "ko": "일정 변경할 수 있을까요?", "level": "B1"},
        {"en": "I'll send you the details by email.", "ko": "이메일로 상세 내용 보낼게요.", "level": "B1"},
        {"en": "Please find attached the report.", "ko": "보고서 첨부해 드립니다.", "level": "B1"},
        {"en": "I look forward to your reply.", "ko": "답변 기다리겠습니다.", "level": "B1"},
        {"en": "Thank you for your time.", "ko": "시간 내주셔서 감사합니다.", "level": "A2"},
        {"en": "Let's touch base next week.", "ko": "다음 주에 연락해요.", "level": "B1"},
        {"en": "I'll follow up on this.", "ko": "이건 제가 후속 조치할게요.", "level": "B1"},
    ],

    "emergency_health": [
        {"en": "Help!", "ko": "도와주세요!", "level": "A1"},
        {"en": "Call an ambulance!", "ko": "구급차 불러주세요!", "level": "A2"},
        {"en": "I need a doctor.", "ko": "의사가 필요해요.", "level": "A1"},
        {"en": "Where's the nearest hospital?", "ko": "가장 가까운 병원이 어디예요?", "level": "A2"},
        {"en": "I'm not feeling well.", "ko": "몸이 안 좋아요.", "level": "A1"},
        {"en": "I have a headache.", "ko": "두통이 있어요.", "level": "A1"},
        {"en": "I have a stomachache.", "ko": "배가 아파요.", "level": "A1"},
        {"en": "I have a fever.", "ko": "열이 있어요.", "level": "A1"},
        {"en": "I feel dizzy.", "ko": "어지러워요.", "level": "A2"},
        {"en": "I think I'm going to be sick.", "ko": "토할 것 같아요.", "level": "A2"},
        {"en": "I cut my finger.", "ko": "손가락을 베었어요.", "level": "A2"},
        {"en": "I hurt my leg.", "ko": "다리를 다쳤어요.", "level": "A2"},
        {"en": "I'm allergic to penicillin.", "ko": "페니실린 알레르기가 있어요.", "level": "B1"},
        {"en": "I need my prescription filled.", "ko": "처방전 조제해 주세요.", "level": "B1"},
        {"en": "How many times a day should I take this?", "ko": "이거 하루에 몇 번 먹어야 해요?", "level": "A2"},
        {"en": "Take it after meals.", "ko": "식후에 드세요.", "level": "A2"},
        {"en": "Are there any side effects?", "ko": "부작용이 있나요?", "level": "B1"},
        {"en": "I lost my medication.", "ko": "약을 잃어버렸어요.", "level": "A2"},
        {"en": "I need to see a specialist.", "ko": "전문의를 봐야 해요.", "level": "B1"},
        {"en": "When can I get an appointment?", "ko": "언제 예약 가능해요?", "level": "A2"},
        {"en": "It hurts here.", "ko": "여기가 아파요.", "level": "A1"},
        {"en": "The pain is getting worse.", "ko": "통증이 심해지고 있어요.", "level": "A2"},
        {"en": "I've had this pain for three days.", "ko": "3일 동안 아팠어요.", "level": "A2"},
        {"en": "Do I need surgery?", "ko": "수술이 필요한가요?", "level": "B1"},
        {"en": "Will I need to stay overnight?", "ko": "입원해야 하나요?", "level": "B1"},
        {"en": "Is it serious?", "ko": "심각한가요?", "level": "A2"},
        {"en": "I need a sick note.", "ko": "진단서가 필요해요.", "level": "B1"},
        {"en": "My insurance will cover it.", "ko": "보험 처리 될 거예요.", "level": "B1"},
        {"en": "Where's the pharmacy?", "ko": "약국 어디예요?", "level": "A2"},
        {"en": "Do I need a prescription for this?", "ko": "이거 처방전 필요해요?", "level": "B1"},
    ],

    "opinions_feelings": [
        {"en": "I think so.", "ko": "그렇게 생각해요.", "level": "A1"},
        {"en": "I don't think so.", "ko": "그렇게 생각 안 해요.", "level": "A1"},
        {"en": "In my opinion...", "ko": "제 생각에는...", "level": "B1"},
        {"en": "I believe that...", "ko": "저는 ~라고 믿어요.", "level": "B1"},
        {"en": "From my point of view...", "ko": "제 관점에서는...", "level": "B1"},
        {"en": "I agree with you.", "ko": "동의해요.", "level": "A2"},
        {"en": "I disagree.", "ko": "동의하지 않아요.", "level": "A2"},
        {"en": "That's true.", "ko": "맞아요.", "level": "A1"},
        {"en": "That's not true.", "ko": "사실이 아니에요.", "level": "A2"},
        {"en": "I'm not sure.", "ko": "잘 모르겠어요.", "level": "A1"},
        {"en": "I have no idea.", "ko": "전혀 모르겠어요.", "level": "A2"},
        {"en": "It depends.", "ko": "상황에 따라 달라요.", "level": "A2"},
        {"en": "I'm happy about it.", "ko": "기뻐요.", "level": "A1"},
        {"en": "I'm sad.", "ko": "슬퍼요.", "level": "A1"},
        {"en": "I'm angry.", "ko": "화나요.", "level": "A1"},
        {"en": "I'm worried.", "ko": "걱정돼요.", "level": "A2"},
        {"en": "I'm excited.", "ko": "신나요.", "level": "A2"},
        {"en": "I'm disappointed.", "ko": "실망했어요.", "level": "A2"},
        {"en": "I'm confused.", "ko": "헷갈려요.", "level": "A2"},
        {"en": "I'm surprised.", "ko": "놀랐어요.", "level": "A2"},
        {"en": "I'm interested in...", "ko": "~에 관심 있어요.", "level": "A2"},
        {"en": "I'm bored.", "ko": "지루해요.", "level": "A1"},
        {"en": "I'm frustrated.", "ko": "답답해요.", "level": "B1"},
        {"en": "I'm relieved.", "ko": "안심했어요.", "level": "B1"},
        {"en": "I'm impressed.", "ko": "인상적이에요.", "level": "B1"},
        {"en": "That's amazing!", "ko": "대단해요!", "level": "A2"},
        {"en": "That's terrible!", "ko": "끔찍해요!", "level": "A2"},
        {"en": "That's interesting.", "ko": "흥미롭네요.", "level": "A2"},
        {"en": "That sounds great!", "ko": "좋아요!", "level": "A2"},
        {"en": "I'm looking forward to it.", "ko": "기대돼요.", "level": "A2"},
    ],
}


def generate_all_sentences():
    """모든 예문 데이터 생성"""
    all_sentences = []

    for category, sentences in SENTENCES_BY_CATEGORY.items():
        # 카테고리 정보 추가
        for sent in sentences:
            sent["category"] = category
            all_sentences.append(sent)

        # 카테고리별 파일 저장
        cat_file = OUTPUT_DIR / f"sentences_{category}.json"
        with open(cat_file, "w", encoding="utf-8") as f:
            json.dump(sentences, f, ensure_ascii=False, indent=2)
        print(f"{category}: {len(sentences)} sentences")

    # 전체 파일 저장
    all_file = OUTPUT_DIR / "sentences_all.json"
    with open(all_file, "w", encoding="utf-8") as f:
        json.dump({
            "total": len(all_sentences),
            "categories": list(SENTENCES_BY_CATEGORY.keys()),
            "sentences": all_sentences
        }, f, ensure_ascii=False, indent=2)

    # 레벨별 통계
    level_stats = {}
    for sent in all_sentences:
        level = sent.get("level", "A1")
        level_stats[level] = level_stats.get(level, 0) + 1

    print(f"\nTotal: {len(all_sentences)} sentences")
    print("By level:")
    for level, count in sorted(level_stats.items()):
        print(f"  {level}: {count}")

    return len(all_sentences)


if __name__ == "__main__":
    print("=" * 60)
    print("예문 데이터 생성")
    print("=" * 60)
    generate_all_sentences()
    print("Done!")
