#!/usr/bin/env python3
"""
일상 영어 표현 데이터 생성 - 700개+
"""
import json
from pathlib import Path

DATA_DIR = Path(__file__).parent.parent / "data"
OUTPUT_FILE = DATA_DIR / "rag_chunks" / "expressions_chunks.json"

# 카테고리별 표현
EXPRESSIONS = {
    "greeting": [
        ("How's it going?", "어떻게 지내?", "informal"),
        ("What's up?", "뭐해?", "informal"),
        ("Long time no see!", "오랜만이야!", "informal"),
        ("Nice to meet you.", "만나서 반갑습니다.", "formal"),
        ("How have you been?", "어떻게 지냈어?", "neutral"),
        ("Good morning!", "좋은 아침!", "neutral"),
        ("Have a nice day!", "좋은 하루 보내!", "neutral"),
        ("Take care!", "잘 가!", "informal"),
        ("See you later!", "나중에 봐!", "informal"),
        ("Catch you later!", "나중에 연락해!", "informal"),
        ("It's been a while.", "오랜만이네요.", "neutral"),
        ("How's everything?", "모든 게 어때?", "informal"),
        ("What brings you here?", "여긴 어떻게 왔어?", "neutral"),
        ("Pleasure to meet you.", "만나서 영광입니다.", "formal"),
        ("I've heard a lot about you.", "많이 들었어요.", "formal"),
    ],
    "cafe": [
        ("Can I get a latte, please?", "라떼 하나 주세요.", "polite"),
        ("I'd like an iced Americano.", "아이스 아메리카노 주세요.", "polite"),
        ("For here or to go?", "드시고 가세요, 가져가세요?", "service"),
        ("Can I have it with oat milk?", "오트밀크로 해주실 수 있나요?", "polite"),
        ("Could you make it less sweet?", "덜 달게 해주실 수 있나요?", "polite"),
        ("Do you have any decaf options?", "디카페인 있나요?", "polite"),
        ("What's your most popular drink?", "제일 인기 있는 음료가 뭐예요?", "polite"),
        ("I'll have what she's having.", "저 분이랑 같은 걸로 주세요.", "informal"),
        ("Keep the change.", "잔돈은 됐어요.", "informal"),
        ("Can I get a refill?", "리필 되나요?", "polite"),
        ("Is there Wi-Fi here?", "여기 와이파이 있나요?", "polite"),
        ("What's the Wi-Fi password?", "와이파이 비밀번호가 뭐예요?", "polite"),
        ("Do you have any outlets?", "콘센트 있나요?", "polite"),
        ("Can I sit outside?", "밖에 앉아도 되나요?", "polite"),
        ("How long is the wait?", "얼마나 기다려야 해요?", "polite"),
    ],
    "restaurant": [
        ("Table for two, please.", "두 명이요.", "polite"),
        ("Do you have a reservation?", "예약하셨나요?", "service"),
        ("Can I see the menu?", "메뉴판 좀 볼 수 있을까요?", "polite"),
        ("What do you recommend?", "뭘 추천하세요?", "polite"),
        ("I'm allergic to nuts.", "견과류 알레르기가 있어요.", "informative"),
        ("Is this dish spicy?", "이 음식 매워요?", "polite"),
        ("Can I have the check, please?", "계산서 주세요.", "polite"),
        ("We'd like to split the bill.", "따로 계산할게요.", "polite"),
        ("Could we have some more water?", "물 좀 더 주시겠어요?", "polite"),
        ("This is delicious!", "이거 정말 맛있네요!", "compliment"),
        ("I'll have the same thing.", "저도 같은 걸로요.", "ordering"),
        ("Can I get this to go?", "포장해 주실 수 있나요?", "polite"),
        ("Is service included?", "서비스료 포함인가요?", "polite"),
        ("Do you take credit cards?", "카드 되나요?", "polite"),
        ("What's the special today?", "오늘의 특선이 뭐예요?", "polite"),
    ],
    "shopping": [
        ("I'm just looking, thanks.", "그냥 구경 중이에요, 감사해요.", "polite"),
        ("Do you have this in a smaller size?", "더 작은 사이즈 있나요?", "polite"),
        ("Can I try this on?", "입어봐도 될까요?", "polite"),
        ("Where's the fitting room?", "탈의실 어디예요?", "polite"),
        ("How much is this?", "이거 얼마예요?", "polite"),
        ("Is this on sale?", "이거 세일 중인가요?", "polite"),
        ("Do you have any discounts?", "할인 있나요?", "polite"),
        ("Can I get a refund?", "환불 가능한가요?", "polite"),
        ("I'd like to exchange this.", "이거 교환하고 싶어요.", "polite"),
        ("Do you have a receipt?", "영수증 있으세요?", "service"),
        ("I'll take it!", "이걸로 할게요!", "decision"),
        ("Let me think about it.", "생각 좀 해볼게요.", "polite"),
        ("What's your return policy?", "환불 정책이 어떻게 되나요?", "polite"),
        ("Is there a warranty?", "보증이 있나요?", "polite"),
        ("Can you gift wrap this?", "선물 포장해 주실 수 있나요?", "polite"),
    ],
    "transport": [
        ("How do I get to the station?", "역에 어떻게 가요?", "asking"),
        ("Which platform for Seoul?", "서울행 몇 번 승강장이에요?", "asking"),
        ("Is this seat taken?", "이 자리 있나요?", "polite"),
        ("When's the next train?", "다음 기차 언제예요?", "asking"),
        ("Does this bus go to downtown?", "이 버스 시내 가나요?", "asking"),
        ("How many stops to get there?", "거기까지 몇 정거장이에요?", "asking"),
        ("Please let me know when we arrive.", "도착하면 알려주세요.", "request"),
        ("I missed my stop!", "정거장을 지나쳤어요!", "exclamation"),
        ("Can you call me a taxi?", "택시 불러주실 수 있나요?", "request"),
        ("Keep the meter running.", "미터기 켜 놓으세요.", "instruction"),
        ("Drop me off here, please.", "여기서 내려주세요.", "request"),
        ("How long will it take?", "얼마나 걸려요?", "asking"),
        ("Is there traffic?", "차가 막히나요?", "asking"),
        ("Where can I buy a ticket?", "표 어디서 사요?", "asking"),
        ("I need a round-trip ticket.", "왕복 표 필요해요.", "request"),
    ],
    "hotel": [
        ("I have a reservation under Kim.", "김으로 예약했어요.", "check-in"),
        ("Can I check in early?", "일찍 체크인 가능한가요?", "request"),
        ("What time is checkout?", "체크아웃 몇 시예요?", "asking"),
        ("Can I have a late checkout?", "늦은 체크아웃 가능한가요?", "request"),
        ("Is breakfast included?", "아침 포함인가요?", "asking"),
        ("Where's the gym?", "헬스장 어디예요?", "asking"),
        ("The Wi-Fi isn't working.", "와이파이가 안 돼요.", "complaint"),
        ("Could I get extra towels?", "수건 좀 더 주실 수 있나요?", "request"),
        ("The air conditioning is broken.", "에어컨이 고장났어요.", "complaint"),
        ("Is there a safe in the room?", "방에 금고 있나요?", "asking"),
        ("Can I store my luggage?", "짐 맡길 수 있나요?", "request"),
        ("Do you have room service?", "룸서비스 되나요?", "asking"),
        ("I'd like to extend my stay.", "숙박 연장하고 싶어요.", "request"),
        ("Can you recommend a restaurant?", "식당 추천해 주실 수 있나요?", "request"),
        ("How do I get to the airport?", "공항에 어떻게 가나요?", "asking"),
    ],
    "airport": [
        ("Where's the check-in counter?", "체크인 카운터 어디예요?", "asking"),
        ("I'd like a window seat.", "창가 자리 부탁드려요.", "request"),
        ("How much is the baggage fee?", "수하물 요금 얼마예요?", "asking"),
        ("My flight is delayed.", "제 비행기가 지연됐어요.", "informative"),
        ("Where's gate 23?", "23번 게이트 어디예요?", "asking"),
        ("When does boarding start?", "탑승 언제 시작해요?", "asking"),
        ("Is this the right gate?", "이 게이트 맞나요?", "asking"),
        ("I have a connecting flight.", "환승편이 있어요.", "informative"),
        ("I lost my passport!", "여권을 잃어버렸어요!", "emergency"),
        ("Where's the baggage claim?", "수하물 찾는 곳 어디예요?", "asking"),
        ("My luggage is missing.", "제 짐이 없어졌어요.", "complaint"),
        ("Where's customs?", "세관 어디예요?", "asking"),
        ("Do I need to declare anything?", "신고할 것이 있나요?", "asking"),
        ("Where can I exchange money?", "환전 어디서 해요?", "asking"),
        ("Is there a shuttle to the city?", "시내 셔틀 있나요?", "asking"),
    ],
    "business": [
        ("Let's schedule a meeting.", "회의 일정 잡읍시다.", "proposal"),
        ("Can we reschedule?", "일정 변경 가능할까요?", "request"),
        ("I'll send you the details.", "자세한 내용 보내드릴게요.", "promise"),
        ("Let me get back to you on that.", "그건 확인 후 연락드릴게요.", "response"),
        ("What's the deadline?", "마감이 언제예요?", "asking"),
        ("I need more time.", "시간이 더 필요해요.", "request"),
        ("Can you clarify that?", "좀 더 설명해 주시겠어요?", "request"),
        ("I see your point.", "말씀하신 뜻을 알겠습니다.", "understanding"),
        ("That's a good idea.", "좋은 생각이에요.", "agreement"),
        ("I have a different opinion.", "저는 다른 의견이 있어요.", "disagreement"),
        ("Let's discuss this further.", "이건 더 논의합시다.", "proposal"),
        ("I'll take care of it.", "제가 처리할게요.", "commitment"),
        ("Please keep me updated.", "계속 알려주세요.", "request"),
        ("We're on the same page.", "우리 의견이 같네요.", "agreement"),
        ("Let's wrap this up.", "마무리합시다.", "closing"),
    ],
    "phone": [
        ("Hello, this is John speaking.", "안녕하세요, 존입니다.", "greeting"),
        ("May I speak to Sarah?", "사라 씨 바꿔주세요.", "request"),
        ("She's not available right now.", "지금 통화 불가능해요.", "response"),
        ("Can I take a message?", "메시지 남기시겠어요?", "offer"),
        ("I'll call back later.", "나중에 다시 전화할게요.", "promise"),
        ("Could you speak up?", "좀 더 크게 말해주시겠어요?", "request"),
        ("The connection is bad.", "연결 상태가 안 좋아요.", "complaint"),
        ("I can't hear you.", "안 들려요.", "complaint"),
        ("Let me transfer your call.", "전화 연결해드릴게요.", "service"),
        ("Please hold.", "잠시만 기다려주세요.", "request"),
        ("Sorry, wrong number.", "죄송해요, 잘못 걸었네요.", "apology"),
        ("I'll email you instead.", "대신 이메일 보낼게요.", "alternative"),
        ("Can I call you back?", "제가 다시 전화해도 될까요?", "request"),
        ("Thanks for calling.", "전화 주셔서 감사합니다.", "closing"),
        ("Talk to you soon.", "곧 연락해요.", "closing"),
    ],
    "emergency": [
        ("Help!", "도와주세요!", "urgent"),
        ("Call an ambulance!", "구급차 불러주세요!", "urgent"),
        ("I need a doctor.", "의사가 필요해요.", "urgent"),
        ("Where's the nearest hospital?", "가장 가까운 병원이 어디예요?", "asking"),
        ("I'm not feeling well.", "몸이 안 좋아요.", "complaint"),
        ("I have a headache.", "머리가 아파요.", "symptom"),
        ("I'm allergic to this.", "이것에 알레르기가 있어요.", "warning"),
        ("I need my medication.", "약이 필요해요.", "urgent"),
        ("There's been an accident.", "사고가 났어요.", "informative"),
        ("Someone call 911!", "누가 911에 전화해요!", "urgent"),
        ("Is everyone okay?", "다들 괜찮아요?", "concern"),
        ("Stay calm.", "침착하세요.", "instruction"),
        ("Don't move.", "움직이지 마세요.", "instruction"),
        ("Help is on the way.", "도움이 오고 있어요.", "reassurance"),
        ("Are you hurt?", "다쳤어요?", "concern"),
    ],
    "opinion": [
        ("I think so too.", "저도 그렇게 생각해요.", "agreement"),
        ("I don't think so.", "전 그렇게 생각 안 해요.", "disagreement"),
        ("In my opinion...", "제 생각에는...", "expressing"),
        ("That makes sense.", "그게 말이 되네요.", "agreement"),
        ("I'm not sure about that.", "그건 잘 모르겠어요.", "uncertainty"),
        ("Absolutely!", "물론이죠!", "strong agreement"),
        ("Not necessarily.", "꼭 그런 건 아니에요.", "partial disagreement"),
        ("That's interesting.", "흥미롭네요.", "neutral"),
        ("I hadn't thought of that.", "그건 생각 못 했어요.", "realization"),
        ("Good point!", "좋은 지적이에요!", "appreciation"),
        ("I see what you mean.", "무슨 말인지 알겠어요.", "understanding"),
        ("Let me think about it.", "생각 좀 해볼게요.", "consideration"),
        ("You have a point.", "일리가 있네요.", "acknowledgment"),
        ("I couldn't agree more.", "전적으로 동의해요.", "strong agreement"),
        ("That's debatable.", "그건 논쟁의 여지가 있어요.", "uncertainty"),
    ],
    "daily": [
        ("What time is it?", "지금 몇 시예요?", "asking"),
        ("I'm running late.", "늦고 있어요.", "informative"),
        ("Let's grab lunch.", "점심 먹자.", "invitation"),
        ("I'm so tired.", "너무 피곤해.", "feeling"),
        ("I need a break.", "휴식이 필요해.", "need"),
        ("What's for dinner?", "저녁 뭐 먹어?", "asking"),
        ("I'll be right back.", "금방 돌아올게.", "promise"),
        ("Wait for me!", "나 기다려!", "request"),
        ("Never mind.", "신경 쓰지 마.", "dismissal"),
        ("It doesn't matter.", "상관없어.", "indifference"),
        ("That's fine with me.", "저는 괜찮아요.", "agreement"),
        ("I'm on my way.", "지금 가는 중이야.", "informative"),
        ("I got stuck in traffic.", "차가 막혔어.", "excuse"),
        ("Let's call it a day.", "오늘은 여기까지 하자.", "closing"),
        ("See you tomorrow.", "내일 봐.", "farewell"),
    ],
    "compliment": [
        ("You look great!", "멋져 보여!", "appearance"),
        ("Nice job!", "잘했어!", "work"),
        ("I love your outfit.", "옷 너무 예쁘다.", "appearance"),
        ("You're so talented.", "너 진짜 재능 있어.", "ability"),
        ("That's amazing!", "대단하다!", "general"),
        ("Well done!", "잘했어!", "work"),
        ("I'm impressed.", "감동받았어.", "general"),
        ("You did great.", "정말 잘했어.", "work"),
        ("I like your style.", "네 스타일 좋아.", "general"),
        ("That's brilliant!", "훌륭해!", "general"),
        ("You're the best.", "네가 최고야.", "general"),
        ("Keep up the good work.", "계속 잘해.", "encouragement"),
        ("You make it look easy.", "너는 쉬워 보이게 해.", "ability"),
        ("I admire your work.", "네 일을 존경해.", "work"),
        ("You have great taste.", "센스 좋다.", "general"),
    ],
    "apology": [
        ("I'm sorry.", "미안해요.", "basic"),
        ("I apologize.", "사과드립니다.", "formal"),
        ("My bad.", "내 잘못이야.", "informal"),
        ("I didn't mean to.", "그러려던 게 아니었어.", "explanation"),
        ("Please forgive me.", "용서해 주세요.", "request"),
        ("I take full responsibility.", "전적으로 제 책임이에요.", "formal"),
        ("It won't happen again.", "다시는 안 그럴게요.", "promise"),
        ("I feel terrible about it.", "정말 죄송해요.", "sincere"),
        ("How can I make it up to you?", "어떻게 보상해 드릴까요?", "offer"),
        ("I should have been more careful.", "더 조심했어야 했어요.", "reflection"),
        ("Sorry for the inconvenience.", "불편을 끼쳐 죄송합니다.", "formal"),
        ("I owe you an apology.", "사과드려야겠어요.", "formal"),
        ("Can you forgive me?", "용서해 줄 수 있어?", "request"),
        ("I'm truly sorry.", "정말 진심으로 사과해요.", "sincere"),
        ("Let me make it right.", "제가 바로잡을게요.", "offer"),
    ],
    "thanks": [
        ("Thank you so much!", "정말 감사합니다!", "strong"),
        ("Thanks a lot.", "정말 고마워.", "informal"),
        ("I really appreciate it.", "정말 감사해요.", "sincere"),
        ("You're too kind.", "너무 친절하시네요.", "response"),
        ("I owe you one.", "신세 졌어.", "informal"),
        ("Thanks for your help.", "도와줘서 고마워.", "specific"),
        ("I can't thank you enough.", "정말 감사해도 다 못해요.", "strong"),
        ("You're a lifesaver!", "네 덕분에 살았어!", "informal"),
        ("Much appreciated.", "정말 감사합니다.", "formal"),
        ("Thanks for everything.", "모든 것에 감사해요.", "general"),
        ("You're the best.", "네가 최고야.", "informal"),
        ("I'm grateful.", "감사해요.", "sincere"),
        ("How thoughtful!", "정말 사려 깊네요!", "appreciation"),
        ("That means a lot to me.", "정말 큰 의미예요.", "sincere"),
        ("Thanks for being there.", "함께해 줘서 고마워.", "personal"),
    ],
    "request": [
        ("Could you help me?", "도와주실 수 있나요?", "polite"),
        ("Would you mind...?", "...해주시겠어요?", "polite"),
        ("Can I ask you a favor?", "부탁 하나 해도 될까요?", "request"),
        ("Do you have a minute?", "잠깐 시간 있어요?", "polite"),
        ("I need your help.", "도움이 필요해요.", "direct"),
        ("If it's not too much trouble...", "너무 번거롭지 않다면...", "polite"),
        ("Would it be possible to...?", "...하는 게 가능할까요?", "formal"),
        ("I was wondering if you could...", "혹시 ...해주실 수 있을까요?", "polite"),
        ("Could you do me a favor?", "부탁 하나만 할게요.", "request"),
        ("I'd really appreciate it if...", "...해주시면 정말 감사하겠어요.", "polite"),
        ("Please let me know.", "알려주세요.", "request"),
        ("Can you lend me a hand?", "좀 도와줄 수 있어?", "informal"),
        ("I hate to bother you, but...", "귀찮게 해서 미안한데...", "polite"),
        ("When you get a chance...", "시간 되실 때...", "polite"),
        ("Could I trouble you for...?", "...해주시면 안 될까요?", "formal"),
    ],
}

def main():
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    chunks = []
    for category, expressions in EXPRESSIONS.items():
        for english, korean, tone in expressions:
            chunk = {
                "id": f"expr_{category}_{len(chunks)}",
                "text": f"{english} - {korean}",
                "english": english,
                "korean": korean,
                "type": "expression",
                "category": category,
                "tone": tone,
                "source": "generated_expressions",
                "level": "A2" if tone in ["basic", "informal"] else "B1"
            }
            chunks.append(chunk)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(chunks, f, ensure_ascii=False, indent=2)

    print(f"총 {len(chunks)}개 표현 생성")
    print(f"저장: {OUTPUT_FILE}")

    # 카테고리별 통계
    stats = {}
    for c in chunks:
        cat = c["category"]
        stats[cat] = stats.get(cat, 0) + 1

    print("\n카테고리별:")
    for k, v in sorted(stats.items(), key=lambda x: -x[1]):
        print(f"  {k}: {v}")

if __name__ == "__main__":
    main()
