// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClM7qGa4YbyG9Xw9C0XRov8XPWFW-r85I',
    appId: '1:900613282617:web:00648d6f889b8cd23866e8',
    messagingSenderId: '900613282617',
    projectId: 'gothic-space-672',
    authDomain: 'gothic-space-672.firebaseapp.com',
    storageBucket: 'gothic-space-672.firebasestorage.app',
    measurementId: 'G-FFBPJCG5Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc7f2LGRfHrVxxhc_81hvOW7kOEeW6asE',
    appId: '1:900613282617:android:f57701ac3bae85893866e8',
    messagingSenderId: '900613282617',
    projectId: 'gothic-space-672',
    storageBucket: 'gothic-space-672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASzL0A45mtuJAyFywS9LCO0bFVBUdmA6Q',
    appId: '1:900613282617:ios:6b69f0e0ff4872d53866e8',
    messagingSenderId: '900613282617',
    projectId: 'gothic-space-672',
    storageBucket: 'gothic-space-672.firebasestorage.app',
    iosClientId:
        '900613282617-69sarflhfd2obqf87dn0i6ievjrvevqo.apps.googleusercontent.com',
    iosBundleId: 'com.buelmanager.flu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASzL0A45mtuJAyFywS9LCO0bFVBUdmA6Q',
    appId: '1:900613282617:ios:243980576bc609273866e8',
    messagingSenderId: '900613282617',
    projectId: 'gothic-space-672',
    storageBucket: 'gothic-space-672.firebasestorage.app',
    iosClientId:
        '900613282617-rv8k7ilm7sivk9v2s4db11au32bbp43j.apps.googleusercontent.com',
    iosBundleId: 'com.buelmanager.flu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDv3OqiXzREI_0yCWUeqmOm7NcffX2F5Q',
    appId: '1:900613282617:web:0600dde5904808e93866e8',
    messagingSenderId: '900613282617',
    projectId: 'gothic-space-672',
    authDomain: 'gothic-space-672.firebaseapp.com',
    storageBucket: 'gothic-space-672.firebasestorage.app',
    measurementId: 'G-TXWCZ995WC',
  );
}
